"""Tests for TemplateChannelDatabase write methods."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from osprey.services.channel_finder.core.base_database import DatabaseWriteError
from osprey.services.channel_finder.databases.template import ChannelDatabase


@pytest.fixture()
def template_db(tmp_path: Path) -> ChannelDatabase:
    """Create a template database with one template and one standalone entry."""
    db_path = tmp_path / "template.json"
    data = {
        "facility_name": "Test Facility",
        "channels": [
            {
                "template": True,
                "base_name": "Dipole",
                "instances": [1, 3],
                "sub_channels": ["SP", "RB"],
                "description": "Dipole {instance:02d}",
            },
            {
                "channel": "STANDALONE:CH",
                "address": "STANDALONE:CH",
                "description": "A standalone channel",
            },
        ],
    }
    db_path.write_text(json.dumps(data, indent=2))
    return ChannelDatabase(str(db_path))


@pytest.fixture()
def template_db_list_format(tmp_path: Path) -> ChannelDatabase:
    """Create a template database in bare list format (no metadata)."""
    db_path = tmp_path / "template_list.json"
    data = [
        {"channel": "SOLO:CH", "address": "SOLO:CH", "description": "Solo"},
    ]
    db_path.write_text(json.dumps(data, indent=2))
    return ChannelDatabase(str(db_path))


class TestSerialize:
    def test_serialize_dict_format_round_trips(self, template_db: ChannelDatabase):
        result = template_db._serialize()
        assert isinstance(result, dict)
        assert result["facility_name"] == "Test Facility"
        assert "channels" in result
        assert len(result["channels"]) == 2  # 1 template + 1 standalone

    def test_serialize_list_format_round_trips(
        self, template_db_list_format: ChannelDatabase
    ):
        result = template_db_list_format._serialize()
        assert isinstance(result, list)
        assert len(result) == 1
        assert result[0]["channel"] == "SOLO:CH"


class TestAddChannel:
    def test_add_standalone_channel(self, template_db: ChannelDatabase):
        result = template_db.add_channel(
            "NEW:CH", address="NEW:CH", description="New channel"
        )

        assert result["success"] is True
        assert template_db.validate_channel("NEW:CH")
        # Persisted to disk
        on_disk = json.loads(Path(template_db.db_path).read_text())
        standalone_names = [
            e["channel"] for e in on_disk["channels"] if not e.get("template")
        ]
        assert "NEW:CH" in standalone_names

    def test_add_duplicate_raises(self, template_db: ChannelDatabase):
        with pytest.raises(DatabaseWriteError, match="already exists"):
            template_db.add_channel("STANDALONE:CH")

    def test_add_duplicate_of_expanded_raises(self, template_db: ChannelDatabase):
        # Dipole01SP is generated by the template
        with pytest.raises(DatabaseWriteError, match="already exists"):
            template_db.add_channel("Dipole01SP")


class TestDeleteChannel:
    def test_delete_standalone_channel(self, template_db: ChannelDatabase):
        result = template_db.delete_channel("STANDALONE:CH")

        assert result["success"] is True
        assert not template_db.validate_channel("STANDALONE:CH")

    def test_delete_template_generated_raises(self, template_db: ChannelDatabase):
        with pytest.raises(DatabaseWriteError, match="template-generated"):
            template_db.delete_channel("Dipole01SP")

    def test_delete_nonexistent_raises(self, template_db: ChannelDatabase):
        with pytest.raises(DatabaseWriteError, match="not found"):
            template_db.delete_channel("NONEXISTENT")


class TestUpdateChannel:
    def test_update_standalone_channel(self, template_db: ChannelDatabase):
        result = template_db.update_channel(
            "STANDALONE:CH", new_description="Updated", new_address="NEW:ADDR"
        )

        assert result["success"] is True
        entry = template_db.get_channel("STANDALONE:CH")
        assert entry["description"] == "Updated"
        assert entry["address"] == "NEW:ADDR"

    def test_update_template_generated_raises(self, template_db: ChannelDatabase):
        with pytest.raises(DatabaseWriteError, match="template-generated"):
            template_db.update_channel("Dipole01SP", new_description="nope")

    def test_update_nonexistent_raises(self, template_db: ChannelDatabase):
        with pytest.raises(DatabaseWriteError, match="not found"):
            template_db.update_channel("NONEXISTENT", new_description="nope")
