"""Model variables, bindings and manifest channels are one population.

Three documents describe the served accelerator from three sides. The channel
manifest says which addresses a deployment serves and which of them the physics
is coupled to. ``va_bindings.json`` says what each coupled address does to the
deck. The model's variable catalog is what the IOC actually writes through.
None of the three is derived from the address text, and each is generated by a
different step -- so the thing that can go wrong between them is not a bad value
but a mismatched *population*: a coupled channel nothing binds, a bound address
the deployment never serves, two bindings writing one element field, a monitor
the bridge cannot tell from its neighbour.

Every one of those is silent at boot and wrong forever after, which is why the
parity is pinned here rather than left to whichever consumer trips over it
first. What is checked is the correspondence itself -- one binding, one
variable, one served channel -- never how many of each there are: a count is
this facility's, and the correspondence is every facility's.

The tree is the demo facility's, generated rather than hand written, so this
runs against a real population of some hundreds rather than a fixture's
handful. No family name appears below.
"""

from __future__ import annotations

import pytest

from osprey.services.virtual_accelerator.bindings import BindingsDocument, load_bindings, setpoints
from osprey.services.virtual_accelerator.manifest import (
    PARTITION_PYAT_COUPLED,
    build_manifest,
)
from osprey.services.virtual_accelerator.manifest.classify import setpoint_addresses
from osprey.services.virtual_accelerator.manifest.paths import PACKAGE_PATHS
from osprey.services.virtual_accelerator.model.pyat import PyATRingModel


@pytest.fixture(scope="module")
def document() -> BindingsDocument:
    return load_bindings(PACKAGE_PATHS.va_bindings)


@pytest.fixture(scope="module")
def channels() -> list[dict]:
    return build_manifest()["channels"]


@pytest.fixture(scope="module")
def booted(channels: list[dict]) -> PyATRingModel:
    return PyATRingModel(PACKAGE_PATHS.data_root, channels)


@pytest.fixture(scope="module")
def coupled(channels: list[dict]) -> list[dict]:
    return [channel for channel in channels if channel["partition"] == PARTITION_PYAT_COUPLED]


class TestOneBindingIsOneVariable:
    def test_the_variables_are_exactly_the_documents_addresses(
        self, booted: PyATRingModel, document: BindingsDocument
    ) -> None:
        """Neither side has a member the other does not. Stated as a set
        comparison so a failure names the strays rather than two numbers."""
        assert set(booted.supported_variables) == {
            binding.setpoint_address for binding in document.bindings
        }

    def test_no_address_is_bound_twice(self, document: BindingsDocument) -> None:
        """Two bindings on one address would give one channel two meanings and
        the catalog would keep whichever was built last."""
        addresses = [binding.setpoint_address for binding in document.bindings]
        assert len(set(addresses)) == len(addresses)

    def test_a_variable_is_writable_exactly_when_its_binding_is(
        self, booted: PyATRingModel, document: BindingsDocument
    ) -> None:
        """A monitor that became writable would accept a write into a reading,
        and a setpoint that became read-only would take none at all."""
        assert {
            address: not variable.read_only
            for address, variable in booted.supported_variables.items()
        } == {binding.setpoint_address: binding.is_writable for binding in document.bindings}

    def test_the_key_is_the_control_address_itself(self, booted: PyATRingModel) -> None:
        """Nothing between the manifest, the IOC and the model translates an
        address, so the catalog key is the address as the facility spells it."""
        assert all(
            variable.name == address for address, variable in booted.supported_variables.items()
        )


class TestOneBindingIsOneServedChannel:
    def test_every_bound_address_is_a_channel_the_deployment_serves(
        self, document: BindingsDocument, channels: list[dict]
    ) -> None:
        served = {channel["address"] for channel in channels}
        assert {binding.setpoint_address for binding in document.bindings} <= served

    def test_every_bound_address_is_in_the_partition_the_physics_drives(
        self, document: BindingsDocument, coupled: list[dict]
    ) -> None:
        """A bound channel outside the coupled partition would be served by
        the static half of the namespace and never reach the model at all."""
        assert {binding.setpoint_address for binding in document.bindings} <= {
            channel["address"] for channel in coupled
        }

    def test_every_coupled_setpoint_the_manifest_carries_is_bound(
        self, document: BindingsDocument, coupled: list[dict]
    ) -> None:
        """The direction the boot refuses on: a coupled setpoint the document
        binds to nothing is a write the IOC would route into the model and the
        model has no variable for."""
        assert setpoint_addresses(coupled) <= set(setpoints(document))

    def test_a_readback_the_document_names_is_a_channel_of_the_same_partition(
        self, document: BindingsDocument, coupled: list[dict]
    ) -> None:
        """A readback address is where the write path publishes the value it
        converted back; one outside this partition would be a second, static
        record wearing the same name."""
        addresses = {channel["address"] for channel in coupled}
        named = {
            binding.readback_address
            for binding in document.bindings
            if binding.readback_address is not None
        }
        assert named
        assert named <= addresses


class TestNoTwoBindingsWriteOneThing:
    def test_no_element_field_is_written_by_two_bindings(self, document: BindingsDocument) -> None:
        """Two setpoints on one element field would each undo the other, and
        the machine would follow whichever was written last."""
        written = [
            (binding.element, binding.attribute, binding.index)
            for binding in document.bindings
            if binding.is_writable and binding.element is not None
        ]
        assert written
        assert len(set(written)) == len(written)

    def test_no_element_and_axis_is_read_by_two_monitors(self, document: BindingsDocument) -> None:
        """What the serving bridge refuses: two readings of one axis at one
        element mean one of them could only be dropped."""
        read = [
            (binding.element, binding.attribute)
            for binding in document.bindings
            if binding.kind == "monitor"
        ]
        assert read
        assert len(set(read)) == len(read)

    def test_every_monitor_reads_an_element_the_ring_names_once(
        self, booted: PyATRingModel, document: BindingsDocument
    ) -> None:
        """A reading comes off the solved orbit at one element; a name the
        deck repeats would read an orbit at an element nobody chose."""
        counts: dict[str, int] = {}
        for element in booted.lattice:
            counts[element.FamName] = counts.get(element.FamName, 0) + 1
        monitors = {binding.element for binding in document.bindings if binding.kind == "monitor"}
        assert monitors
        assert sorted(name for name in monitors if counts.get(name, 0) != 1) == []


class TestTheParityIsNotVacuous:
    def test_the_document_binds_something(self, document: BindingsDocument) -> None:
        assert document.bindings

    def test_the_document_both_writes_and_reads(self, document: BindingsDocument) -> None:
        """Every check above would pass on a document of one shape only."""
        assert any(binding.is_writable for binding in document.bindings)
        assert any(binding.kind == "monitor" for binding in document.bindings)

    def test_the_namespace_is_wider_than_the_physics(
        self, channels: list[dict], coupled: list[dict]
    ) -> None:
        """The coupled partition is a subset of the served namespace, so the
        subset assertions above are real restrictions rather than identities
        over one undivided list."""
        assert 0 < len(coupled) < len(channels)
