"""DePlot (Pix2Struct) model wrapper with lazy loading.

Wraps Google's DePlot model for chart-to-table extraction. The model
is loaded lazily on the first extraction request to avoid startup delay.
"""

from __future__ import annotations

import logging
import re
from io import BytesIO
from typing import Any

logger = logging.getLogger("osprey.services.deplot.model")

# Module-level singleton
_processor = None
_model = None

MODEL_NAME = "google/deplot"


def _load_model() -> None:
    """Load DePlot model and processor (lazy, first-call only)."""
    global _processor, _model

    if _model is not None:
        return

    logger.info("Loading DePlot model '%s' (first request — this may take a moment)...", MODEL_NAME)

    from transformers import Pix2StructForConditionalGeneration, Pix2StructProcessor

    _processor = Pix2StructProcessor.from_pretrained(MODEL_NAME)
    _model = Pix2StructForConditionalGeneration.from_pretrained(MODEL_NAME)

    logger.info("DePlot model loaded successfully")


def extract_table(image_bytes: bytes) -> str:
    """Extract a data table from a chart image using DePlot.

    Args:
        image_bytes: Raw image bytes (PNG, JPEG, etc.).

    Returns:
        Raw table string as generated by DePlot (pipe-delimited format).
    """
    from PIL import Image

    _load_model()

    image = Image.open(BytesIO(image_bytes)).convert("RGB")

    inputs = _processor(
        images=image,
        text="Generate underlying data table of the figure below:",
        return_tensors="pt",
    )

    predictions = _model.generate(**inputs, max_new_tokens=512)
    raw_table = _processor.decode(predictions[0], skip_special_tokens=True)

    logger.debug("DePlot raw output: %s", raw_table[:200])
    return raw_table


def parse_table(raw: str) -> dict[str, Any]:
    """Parse DePlot's raw table output into structured data.

    DePlot outputs tables in a pipe-delimited format like:
        ``TITLE | <title> <newline> <col1> | <col2> <newline> val1 | val2 ...``

    Args:
        raw: Raw DePlot output string.

    Returns:
        Dict with keys:
          - ``columns``: list of column header strings
          - ``data``: list of [x, y] pairs (floats where possible)
          - ``raw_table``: the original DePlot output
    """
    lines = [line.strip() for line in raw.strip().split("<0x0A>") if line.strip()]

    # DePlot sometimes uses literal newlines instead of <0x0A>
    if len(lines) <= 1:
        lines = [line.strip() for line in raw.strip().split("\n") if line.strip()]

    title = ""
    columns: list[str] = []
    data: list[list[float | str]] = []

    for i, line in enumerate(lines):
        parts = [p.strip() for p in line.split("|")]

        # First line is often "TITLE | <actual title>"
        if i == 0 and len(parts) >= 2 and parts[0].upper() == "TITLE":
            title = parts[1]
            continue

        # Header row (first non-title row)
        if not columns:
            columns = parts
            continue

        # Data rows
        row: list[float | str] = []
        for val in parts:
            row.append(_try_float(val))
        data.append(row)

    return {
        "title": title,
        "columns": columns,
        "data": data,
        "raw_table": raw,
    }


def _try_float(val: str) -> float | str:
    """Attempt to convert a string to float, handling common formats."""
    cleaned = re.sub(r"[,%\s]", "", val)
    try:
        return float(cleaned)
    except (ValueError, TypeError):
        return val
