"""Semantic checks on a parsed ``mapping.yaml`` against the export it maps.

:func:`~osprey.services.mml.mapping.schema.parse_mapping` checks structure;
this module checks meaning, and ``map --check`` exits non-zero on any problem
it returns. Each rule is one small predicate yielding :class:`Problem` records
keyed by the dotted path of the offending slot.

Rules:

* No ``null`` in the null domain: ``facility.token``; every description at
  facility, system, family and field level; ``class`` of every family with
  ``channels > 0`` and its ``branch`` unless the class is packaged; every
  ``directions.*.direction``.
* The facility token is PN_LOCAL; a ``rename`` is PN_LOCAL.
* ``systems:`` and ``families:`` name exactly the systems and families of
  ``ao.json``.
* A family ``branch`` names a packaged class or a declared branch; a ``class``
  is PN_LOCAL and not the root; a packaged ``class`` takes no ``branch`` other
  than its packaged parent; a new ``class`` shared by families has one branch.
* Every channel-bearing ``(raw family, field)`` has a ``directions`` key, and
  every key names a family of ``families:`` and a field of it in ``ao.json``.
* System names are PN_LOCAL and distinct after ``lower()``; mapped family
  tokens are distinct after ``lower().replace('-', '_')``.
* A declared branch is not named like a packaged class (root included), has a
  packaged or declared parent, and is on no cycle.
* ``section_order`` is a permutation of the system names.
* A ``stated`` direction agrees with a decided vote unless ``override``.
* ``derived`` descriptions are counted per level and ``derived`` directions
  in total; with ``no_derived`` every derived slot is a problem.

A collision is reported at the later entry in document order. The module is
pure and depends on the standard library and the ``mml`` package.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator
from dataclasses import dataclass

from osprey.services.mml.directions import Vote
from osprey.services.mml.family import family_views, system_bodies
from osprey.services.mml.mapping.branches import ROOT_CLASS, is_pn_local, packaged_classes
from osprey.services.mml.mapping.schema import Mapping

__all__ = ["CheckResult", "Problem", "check_mapping"]

#: Provenance marking prose or a direction generated by ``map --init``.
DERIVED = "derived"

#: Provenance marking a slot a person has written or confirmed.
STATED = "stated"

#: Description levels counted in :attr:`CheckResult.derived_descriptions`.
_LEVELS: tuple[str, ...] = ("facility", "system", "family", "field")


@dataclass(frozen=True)
class Problem:
    """One refusal: the offending key path and what is wrong with it."""

    key: str
    message: str

    def __str__(self) -> str:
        """Return ``"<key>: <message>"``, the form ``map --check`` prints."""
        return f"{self.key}: {self.message}"


@dataclass(frozen=True)
class CheckResult:
    """The outcome of :func:`check_mapping`.

    Attributes:
        problems: Every refusal, in rule order and document order within a rule.
        derived_descriptions: ``derived`` descriptions keyed by level
            (``facility``, ``system``, ``family``, ``field``).
        derived_directions: ``derived`` directions.
    """

    problems: list[Problem]
    derived_descriptions: dict[str, int]
    derived_directions: int


class _Context:
    """The export facts every predicate reads, computed once."""

    def __init__(self, mapping: Mapping, ao: dict, votes: dict[tuple[str, str], Vote]) -> None:
        self.mapping = mapping
        self.votes = votes
        self.packaged = packaged_classes()
        self.systems: list[str] = []
        #: raw family -> field names across systems, in first-seen order.
        self.family_fields: dict[str, dict[str, None]] = {}
        for system, families in system_bodies(ao):
            self.systems.append(system)
            for view in family_views(system, families):
                fields = self.family_fields.setdefault(view.raw_name, {})
                for name in view.fields:
                    fields[name] = None

    def known_parent(self, name: str) -> bool:
        """Return whether ``name`` is a packaged class, the root or a declared branch."""
        return name == ROOT_CLASS or name in self.packaged or name in self.mapping.branches


Predicate = Callable[[_Context], Iterator[Problem]]


# -- predicates ---------------------------------------------------------------


def _null_domain(ctx: _Context) -> Iterator[Problem]:
    mapping = ctx.mapping
    if mapping.facility.token is None:
        yield Problem("facility.token", "must not be null")
    if mapping.facility.description is None:
        yield Problem("facility.description", "must not be null")
    for raw, system in mapping.systems.items():
        if system.description is None:
            yield Problem(f"systems.{raw}.description", "must not be null")
    for raw, family in mapping.families.items():
        if family.description is None:
            yield Problem(f"families.{raw}.description", "must not be null")
        for name, fld in family.fields.items():
            if fld.description is None:
                yield Problem(f"families.{raw}.fields.{name}.description", "must not be null")
        if family.channels > 0:
            if family.class_ is None:
                yield Problem(
                    f"families.{raw}.class", "must not be null for a family with channels"
                )
            elif family.class_ not in ctx.packaged and family.branch is None:
                yield Problem(
                    f"families.{raw}.branch",
                    f"must not be null for the new class {family.class_!r}",
                )
    for key, direction in mapping.directions.items():
        if direction.direction is None:
            yield Problem(f"directions.{key}.direction", "must not be null")


def _facility_token(ctx: _Context) -> Iterator[Problem]:
    token = ctx.mapping.facility.token
    if token is not None and not is_pn_local(token):
        yield Problem("facility.token", f"{token!r} is not a valid PN_LOCAL token")


def _unknown_systems(ctx: _Context) -> Iterator[Problem]:
    for raw in ctx.mapping.systems:
        if raw not in ctx.systems:
            yield Problem(f"systems.{raw}", "names a system absent from ao.json")
    for raw in ctx.systems:
        if raw not in ctx.mapping.systems:
            yield Problem(f"systems.{raw}", "ao.json system has no systems: entry")


def _unknown_families(ctx: _Context) -> Iterator[Problem]:
    for raw in ctx.mapping.families:
        if raw not in ctx.family_fields:
            yield Problem(f"families.{raw}", "names a family absent from ao.json")
    for raw in ctx.family_fields:
        if raw not in ctx.mapping.families:
            yield Problem(f"families.{raw}", "ao.json family has no families: entry")


def _renames(ctx: _Context) -> Iterator[Problem]:
    for raw, family in ctx.mapping.families.items():
        if family.rename is not None and not is_pn_local(family.rename):
            yield Problem(
                f"families.{raw}.rename", f"{family.rename!r} is not a valid PN_LOCAL token"
            )


def _branches_of_families(ctx: _Context) -> Iterator[Problem]:
    for raw, family in ctx.mapping.families.items():
        if family.branch is not None and not ctx.known_parent(family.branch):
            yield Problem(
                f"families.{raw}.branch",
                f"{family.branch!r} names neither a packaged class nor a declared branch",
            )


def _classes(ctx: _Context) -> Iterator[Problem]:
    for raw, family in ctx.mapping.families.items():
        klass = family.class_
        if klass is None:
            continue
        if klass == ROOT_CLASS:
            yield Problem(f"families.{raw}.class", f"must not be the root class {ROOT_CLASS!r}")
        elif not is_pn_local(klass):
            yield Problem(f"families.{raw}.class", f"{klass!r} is not a valid PN_LOCAL token")


def _packaged_class_branch(ctx: _Context) -> Iterator[Problem]:
    for raw, family in ctx.mapping.families.items():
        packaged = ctx.packaged.get(family.class_) if family.class_ is not None else None
        if packaged is not None and family.branch not in (None, packaged.parent):
            yield Problem(
                f"families.{raw}.branch",
                f"the packaged class {family.class_!r} has the parent {packaged.parent!r}, "
                f"not {family.branch!r}",
            )


def _shared_new_class(ctx: _Context) -> Iterator[Problem]:
    first: dict[str, tuple[str, str]] = {}
    for raw, family in ctx.mapping.families.items():
        klass, branch = family.class_, family.branch
        if klass is None or branch is None or klass in ctx.packaged or klass == ROOT_CLASS:
            continue
        seen = first.setdefault(klass, (raw, branch))
        if seen[1] != branch:
            yield Problem(
                f"families.{raw}.branch",
                f"the class {klass!r} already has the branch {seen[1]!r} "
                f"on the family {seen[0]!r}, not {branch!r}",
            )


def _missing_direction_groups(ctx: _Context) -> Iterator[Problem]:
    for family, fields in ctx.family_fields.items():
        for name in fields:
            key = f"{family}.{name}"
            if key not in ctx.mapping.directions:
                yield Problem(f"directions.{key}", "signal group has no directions entry")


def _system_names(ctx: _Context) -> Iterator[Problem]:
    folded: dict[str, str] = {}
    for raw, system in ctx.mapping.systems.items():
        if not is_pn_local(system.name):
            yield Problem(f"systems.{raw}.name", f"{system.name!r} is not a valid PN_LOCAL token")
        other = folded.setdefault(system.name.lower(), raw)
        if other != raw:
            yield Problem(
                f"systems.{raw}.name",
                f"{system.name!r} folds to the same lower-case name as systems.{other}",
            )


def _family_prefixes(ctx: _Context) -> Iterator[Problem]:
    folded: dict[str, str] = {}
    for raw in ctx.mapping.families:
        token = ctx.mapping.mapped(raw)
        other = folded.setdefault(token.lower().replace("-", "_"), raw)
        if other != raw:
            yield Problem(
                f"families.{raw}",
                f"mapped token {token!r} folds to the same signal prefix as families.{other}; "
                "set rename on one of them",
            )


def _declared_branches(ctx: _Context) -> Iterator[Problem]:
    branches = ctx.mapping.branches
    for name, branch in branches.items():
        if name == ROOT_CLASS or name in ctx.packaged:
            yield Problem(f"branches.{name}", "is named like a packaged class")
        if not ctx.known_parent(branch.parent):
            yield Problem(
                f"branches.{name}.parent",
                f"{branch.parent!r} names neither a packaged class nor a declared branch",
            )
    for name in branches:
        seen: set[str] = set()
        current = name
        while current in branches and current not in seen:
            seen.add(current)
            current = branches[current].parent
        if current == name:
            yield Problem(f"branches.{name}.parent", "forms a cycle of declared branches")


def _section_order(ctx: _Context) -> Iterator[Problem]:
    names = [system.name for system in ctx.mapping.systems.values()]
    seen: set[str] = set()
    for index, name in enumerate(ctx.mapping.section_order):
        if name not in names:
            yield Problem(f"section_order[{index}]", f"{name!r} is not a system name")
        elif name in seen:
            yield Problem(f"section_order[{index}]", f"{name!r} appears more than once")
        seen.add(name)
    missing = [name for name in names if name not in seen]
    if missing:
        yield Problem("section_order", f"is missing the system names {missing!r}")


def _direction_keys(ctx: _Context) -> Iterator[Problem]:
    for key in ctx.mapping.directions:
        family, _, name = key.partition(".")
        if family not in ctx.mapping.families:
            yield Problem(f"directions.{key}", f"names the family {family!r} absent from families:")
        elif name not in ctx.family_fields.get(family, {}):
            yield Problem(
                f"directions.{key}", f"names the field {name!r} absent from {family!r} in ao.json"
            )


def _stated_against_vote(ctx: _Context) -> Iterator[Problem]:
    for key, direction in ctx.mapping.directions.items():
        if direction.provenance != STATED or direction.direction is None or direction.override:
            continue
        family, _, name = key.partition(".")
        vote = ctx.votes.get((family, name))
        if (
            vote is not None
            and vote.direction is not None
            and vote.direction != direction.direction
        ):
            yield Problem(
                f"directions.{key}",
                f"stated {direction.direction!r} disagrees with the vote {vote.direction!r}; "
                "set override: true to keep it",
            )


_PREDICATES: tuple[Predicate, ...] = (
    _null_domain,
    _facility_token,
    _unknown_systems,
    _unknown_families,
    _renames,
    _branches_of_families,
    _classes,
    _packaged_class_branch,
    _shared_new_class,
    _missing_direction_groups,
    _system_names,
    _family_prefixes,
    _declared_branches,
    _section_order,
    _direction_keys,
    _stated_against_vote,
)


def _level(key: str) -> str:
    """Return the description level of a provenance slot key."""
    if key == "facility":
        return "facility"
    if key.startswith("systems."):
        return "system"
    return "field" if ".fields." in key else "family"


def check_mapping(
    mapping: Mapping,
    ao: dict,
    votes: dict[tuple[str, str], Vote],
    *,
    no_derived: bool,
) -> CheckResult:
    """Check a parsed mapping against the merged export it maps.

    Args:
        mapping: The structurally valid mapping.
        ao: ``{system: {family: body}}``; keys starting with ``_`` and
            non-dict bodies are skipped. Not modified.
        votes: :func:`~osprey.services.mml.directions.vote_directions` of ``ao``.
        no_derived: Report every ``derived`` provenance slot as a problem.

    Returns:
        Every problem found and the derived counts.
    """
    ctx = _Context(mapping, ao, votes)
    problems = [problem for predicate in _PREDICATES for problem in predicate(ctx)]

    descriptions = dict.fromkeys(_LEVELS, 0)
    directions = 0
    derived_keys: list[str] = []
    for key, provenance in mapping.provenance_slots():
        if provenance != DERIVED:
            continue
        derived_keys.append(key)
        if key.startswith("directions."):
            directions += 1
        else:
            descriptions[_level(key)] += 1
    if no_derived:
        problems.extend(
            Problem(f"{key}.provenance", "is derived; review it and mark it stated")
            for key in derived_keys
        )
    return CheckResult(
        problems=problems, derived_descriptions=descriptions, derived_directions=directions
    )
