"""Semantic checks on a parsed ``mapping.yaml`` against the export it maps.

:func:`~osprey.services.mml.mapping.schema.parse_mapping` checks structure;
this module checks meaning, and ``map --check`` exits non-zero on any problem
it returns. Each rule is one small predicate yielding :class:`Problem` records
keyed by the dotted path of the offending slot.

Rules:

* No ``null`` in the null domain: ``facility.token``; every description at
  facility, system, family and field level; ``class`` of every family with
  ``channels > 0`` and its ``branch`` unless the class is packaged; every
  ``directions.*.direction``; every judgment answer the document carries.
* Every judgment answer names a judgment some system pends and every pending
  judgment has an answer slot; a ``field:`` answer mints a name the family can
  carry and is described by a ``families`` entry; a ``device`` answer promotes
  no signal the family binds below its devices.
* Where the tree carries a 2.0 virtual-accelerator export the mapping holds a
  ``virtual_accelerator`` block for the system that export is of, the deck that
  export was sampled over is imported, every answer of the block is one the
  deck's elements can carry, and every family the block couples states a
  hardware nominal for each of its devices to start the model from. A tree
  without such an export asks none of this.
* Every quantity a virtual-accelerator family is asked for is answered with a
  positive number. It is asked for because nothing else states it, so an
  unanswered one stops the emit lane exactly as an unanswered slot does.
* The facility token is PN_LOCAL; a ``rename`` is PN_LOCAL.
* ``systems:`` and ``families:`` name exactly the systems and families of
  ``ao.json``.
* A family ``branch`` names a packaged class or a declared branch; a ``class``
  is PN_LOCAL and not the root; a packaged ``class`` takes no ``branch`` other
  than its packaged parent; a new ``class`` shared by families has one branch.
* Every channel-bearing ``(raw family, field)`` has a ``directions`` key, and
  every key names a family of ``families:`` and a field of it in ``ao.json``.
* System names are PN_LOCAL and distinct after ``lower()``; mapped family
  tokens are distinct after ``lower().replace('-', '_')``.
* A declared branch is not named like a packaged class (root included), has a
  packaged or declared parent, and is on no cycle.
* ``section_order`` is a permutation of the system names.
* A ``stated`` direction agrees with a decided vote unless ``override``.
* ``derived`` descriptions are counted per level and ``derived`` directions
  in total; with ``no_derived`` every derived slot is a problem.

Every export fact a predicate reads comes from the judged views -- the export
with the reviewer's judgment answers applied -- so a field an answer creates
carries the same obligations as an exported one, down to its ``directions``
key, and an answer no export can carry is reported once and then left out of
the grain the rest of the rules see.

A collision is reported at the later entry in document order. The module is
pure and depends on the standard library and the ``mml`` package.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Iterator
from dataclasses import dataclass, replace

from osprey.services.mml.directions import Vote
from osprey.services.mml.family import FamilyView, system_bodies
from osprey.services.mml.judgments import (
    PendingJudgments,
    VAPending,
    all_pending_judgments,
    judged_family_views,
    judged_va_block,
    unanswered_slots,
    validate_answers,
)
from osprey.services.mml.mapping.branches import ROOT_CLASS, is_pn_local, packaged_classes
from osprey.services.mml.mapping.schema import (
    ROWS_BEYOND_KIND,
    SHARED_KIND,
    UNBOUND_KIND,
    FamilyJudgments,
    Mapping,
    OwnerMap,
    SharedAnswer,
    VirtualAccelerator,
    judgment_key,
)
from osprey.services.mml.va.verdicts import missing_nominal

__all__ = ["CheckResult", "Problem", "VAExport", "check_mapping"]

#: Provenance marking prose or a direction generated by ``map --init``.
DERIVED = "derived"

#: Provenance marking a slot a person has written or confirmed.
STATED = "stated"

#: Description levels counted in :attr:`CheckResult.derived_descriptions`.
_LEVELS: tuple[str, ...] = ("facility", "system", "family", "field")


@dataclass(frozen=True)
class Problem:
    """One refusal: the offending key path and what is wrong with it."""

    key: str
    message: str

    def __str__(self) -> str:
        """Return ``"<key>: <message>"``, the form ``map --check`` prints."""
        return f"{self.key}: {self.message}"


@dataclass(frozen=True)
class VAExport:
    """The virtual accelerator a 2.0 export carries, as the tree holds it.

    A mapping is asked about a virtual accelerator only where one was exported,
    so the caller reads the tree and hands over what it found; the rules here
    never open a file. Whether the deck is there is part of what it found: a
    block sampled over a deck nobody imported is a tree the mapping cannot be
    checked against, which is the caller's to report and not to hide.

    Attributes:
        system: The system ``va.json`` carries a block for, which the mapping's
            ``virtual_accelerator`` block is the answer to.
        pending: What the rules ask of that system, decided against the deck,
            ready for
            :func:`~osprey.services.mml.judgments.validate_answers`; ``None``
            when the deck was not imported, which leaves the answers unchecked.
    """

    system: str
    pending: VAPending | None = None


@dataclass(frozen=True)
class CheckResult:
    """The outcome of :func:`check_mapping`.

    Attributes:
        problems: Every refusal, in rule order and document order within a rule.
        derived_descriptions: ``derived`` descriptions keyed by level
            (``facility``, ``system``, ``family``, ``field``).
        derived_directions: ``derived`` directions.
    """

    problems: list[Problem]
    derived_descriptions: dict[str, int]
    derived_directions: int


def _answer_findings(
    pending: dict[tuple[str, str], PendingJudgments],
    mapping: Mapping,
    va: VAPending | None,
) -> list[tuple[str, str, bool]]:
    """Return one ``(key, message, export_incompatible)`` entry per refused answer.

    This is the seam between the judgment rules and the checker. The rules have
    a single home, :func:`osprey.services.mml.judgments.validate_answers`, which
    reads the same pending judgments; the checker renders what it reports and
    takes every export-incompatible answer out of :attr:`_Context.answers`. No
    rule is evaluated here.

    Args:
        pending: What each ``(system, raw family)`` asks its reviewer.
        mapping: The mapping carrying the answers.
        va: What the virtual-accelerator rules ask of the exported system and
            of what, or ``None`` where the tree carries no 2.0 export to ask
            it -- without which the block's answers are not judged at all.

    Returns:
        The refused answers, each keyed by its bracketed document path.
    """
    return list(validate_answers(pending, mapping, va))


def _va_facts(mapping: Mapping, va: VAExport | None) -> VAPending | None:
    """Return the facts the virtual-accelerator answers are judged against.

    They are judged wherever there is a block written for the system that was
    exported. A mapping carrying no block answers nothing and a block naming
    another system answers a question this export never asked; each is one
    problem of its own rather than an answer-by-answer refusal against facts
    the block was never written for.

    Args:
        mapping: The mapping whose block, if any, would be judged.
        va: The virtual accelerator the tree carries.

    Returns:
        What the rules ask of the exported system, or ``None`` when this
        mapping's block is not an answer to it.
    """
    document = mapping.virtual_accelerator
    if va is None or document is None:
        return None
    if document.system is not None and document.system != va.system:
        return None
    return va.pending


def _kept_shared(raw: str, shared: SharedAnswer | None, refused: set[str]) -> SharedAnswer | None:
    """Return one family's shared-PV answer with the refused owners taken out."""
    if shared is None or judgment_key(raw, SHARED_KIND) in refused:
        return None
    if isinstance(shared, OwnerMap):
        return OwnerMap(
            owners={
                group: owner
                for group, owner in shared.owners.items()
                if judgment_key(raw, SHARED_KIND, ordinal=group) not in refused
            }
        )
    return shared


def _kept_answers(raw: str, judgments: FamilyJudgments, refused: set[str]) -> FamilyJudgments:
    """Return one family's answers with the ones at ``refused`` taken out."""
    return replace(
        judgments,
        rows_beyond={
            field: {
                signal: answer
                for signal, answer in answers.items()
                if judgment_key(raw, ROWS_BEYOND_KIND, field, signal) not in refused
            }
            for field, answers in judgments.rows_beyond.items()
        },
        unbound_devices={
            ordinal: answer
            for ordinal, answer in judgments.unbound_devices.items()
            if judgment_key(raw, UNBOUND_KIND, ordinal=ordinal) not in refused
        },
        shared_pvs=_kept_shared(raw, judgments.shared_pvs, refused),
    )


def _without_refused(mapping: Mapping, refused: set[str]) -> Mapping:
    """Return ``mapping`` without the answers keyed by ``refused``.

    An answer the export cannot carry is reported rather than applied, so the
    judged grain below is what the export and the surviving answers say. A key
    naming no answer slot takes nothing out.
    """
    if not refused:
        return mapping
    return replace(
        mapping,
        judgments={
            raw: _kept_answers(raw, judgments, refused)
            for raw, judgments in mapping.judgments.items()
        },
    )


class _Context:
    """The export facts every predicate reads, computed once.

    Attributes:
        mapping: The mapping as parsed, answers and all.
        votes: The direction votes of the raw export.
        packaged: The packaged ontology classes.
        systems: The raw system tokens of the export, in export order.
        pending: What each ``(system, raw family)`` asks its reviewer, read off
            the raw export before any answer is applied.
        va: The virtual accelerator the tree carries, or ``None`` on a tree
            whose export states none.
        judgment_problems: One problem per refused answer, in rule order.
        answers: ``mapping`` without the answers no export can carry; an answer
            whose only problem is a missing mapping entry stays, so the field it
            creates still reaches :attr:`family_fields`.
        judged_views: The family views of each system, ``answers`` applied.
        family_fields: raw family -> judged field names, in first-seen order.
    """

    def __init__(
        self,
        mapping: Mapping,
        ao: dict,
        votes: dict[tuple[str, str], Vote],
        va: VAExport | None = None,
    ) -> None:
        self.mapping = mapping
        self.votes = votes
        self.packaged = packaged_classes()
        bodies = list(system_bodies(ao))
        self.systems: list[str] = [system for system, _ in bodies]
        self.pending = all_pending_judgments(ao)
        self.va = va

        findings = _answer_findings(self.pending, mapping, _va_facts(mapping, va))
        self.judgment_problems: list[Problem] = [
            Problem(key, message) for key, message, _ in findings
        ]
        self.answers = _without_refused(
            mapping, {key for key, _, incompatible in findings if incompatible}
        )

        self.judged_views: dict[str, list[FamilyView]] = {
            system: list(judged_family_views(system, families, self.answers))
            for system, families in bodies
        }
        self.family_fields: dict[str, dict[str, None]] = {}
        for views in self.judged_views.values():
            for view in views:
                fields = self.family_fields.setdefault(view.raw_name, {})
                for name in view.fields:
                    fields[name] = None

    def known_parent(self, name: str) -> bool:
        """Return whether ``name`` is a packaged class, the root or a declared branch."""
        return name == ROOT_CLASS or name in self.packaged or name in self.mapping.branches


Predicate = Callable[[_Context], Iterator[Problem]]


# -- predicates ---------------------------------------------------------------


def _null_domain(ctx: _Context) -> Iterator[Problem]:
    mapping = ctx.mapping
    if mapping.facility.token is None:
        yield Problem("facility.token", "must not be null")
    if mapping.facility.description is None:
        yield Problem("facility.description", "must not be null")
    for raw, system in mapping.systems.items():
        if system.description is None:
            yield Problem(f"systems.{raw}.description", "must not be null")
    for raw, family in mapping.families.items():
        if family.description is None:
            yield Problem(f"families.{raw}.description", "must not be null")
        for name, fld in family.fields.items():
            if fld.description is None:
                yield Problem(f"families.{raw}.fields.{name}.description", "must not be null")
        if family.channels > 0:
            if family.class_ is None:
                yield Problem(
                    f"families.{raw}.class", "must not be null for a family with channels"
                )
            elif family.class_ not in ctx.packaged and family.branch is None:
                yield Problem(
                    f"families.{raw}.branch",
                    f"must not be null for the new class {family.class_!r}",
                )
    for key, direction in mapping.directions.items():
        if direction.direction is None:
            yield Problem(f"directions.{key}.direction", "must not be null")
    for key, message in unanswered_slots(mapping):
        yield Problem(key, message)


def _judgments(ctx: _Context) -> Iterator[Problem]:
    yield from ctx.judgment_problems


def _va_values(ctx: _Context) -> Iterator[Problem]:
    """Refuse a quantity a family was asked for and nobody answered.

    Which quantities a family is asked for is the rule's to say, not the
    document's: the questions are the proposed verdict's own, as
    :func:`_va_nominals` re-asks ``missing_nominal``, so a reviewer who
    deletes the question rather than answering it is refused here instead of
    by the command that needed the number. They are asked only while the
    mapping still couples the family, because a family standing still is
    served nothing to need them for -- which is the rule the emitter reads
    too.

    A quantity is asked for because no part of the export states it, so there
    is nothing to fall back on. Each one is refused in its own words: a
    question the document dropped is not answered, a question it kept and left
    null must not be null, and a number that could not be what it stands for
    -- not finite, or not positive -- is refused beside them, because the
    model would be built on it.

    The traffic runs both ways, as it does for a slot: an entry the rules
    never asked for answers no open question, so a misspelt name is named
    rather than read as an answered question or passed over in silence. That
    is asked of a coupled family alone, because a family the reviewer stands
    still keeps the block the rules wrote for it and is served nothing to need
    any of it for.
    """
    document = ctx.mapping.virtual_accelerator
    pending = _va_facts(ctx.mapping, ctx.va)
    if document is None or pending is None:
        return
    for raw, proposed in pending.proposed.items():
        decided = document.families.get(raw)
        if decided is None or decided.verdict != "couple":
            continue
        for name, asked in proposed.values.items():
            key = f"virtual_accelerator.families.{raw}.values.{name}"
            answered = decided.values.get(name)
            if answered is None:
                yield Problem(key, "is not answered")
            elif answered.answer is None:
                yield Problem(f"{key}.answer", "must not be null")
            elif not math.isfinite(answered.answer) or answered.answer <= 0:
                yield Problem(f"{key}.answer", f"must be a positive number of {asked.units}")
        for name in decided.values:
            if name not in proposed.values:
                yield Problem(
                    f"virtual_accelerator.families.{raw}.values.{name}",
                    f"answers no open question of {raw} in {pending.system}",
                )


def _virtual_accelerator(ctx: _Context) -> Iterator[Problem]:
    va = ctx.va
    if va is None:
        return
    document = ctx.mapping.virtual_accelerator
    if document is None:
        yield Problem(
            "virtual_accelerator",
            f"the {va.system} export carries a virtual accelerator this mapping "
            "decides nothing about; run osprey mml map --init to add the block",
        )
        return
    if document.system is not None and document.system != va.system:
        yield Problem(
            "virtual_accelerator.system",
            f"names {document.system!r}, and the export carries a virtual "
            f"accelerator for {va.system!r}",
        )
    if va.pending is None:
        yield Problem(
            "virtual_accelerator",
            f"the deck {va.system} was sampled over is not in the tree "
            f"(data/mml/lattice/{va.system}.mat), so no answer of the block can "
            "be checked; import the deck beside the export",
        )
        return
    yield from _va_nominals(ctx, va.pending, document)


def _va_nominals(
    ctx: _Context, pending: VAPending, document: VirtualAccelerator
) -> Iterator[Problem]:
    """Report every coupled family the emitter could not start the model from.

    The rule is
    :func:`~osprey.services.mml.va.verdicts.missing_nominal`, the one
    ``map --init`` latched the family on, so a reviewer who couples it back
    reads here what the emitter would otherwise refuse the whole machine for.
    It is asked of the judged block, as the emitter asks it: a device a
    reviewer dropped states nothing any more.
    """
    views = {view.raw_name: view for view in ctx.judged_views.get(pending.system, ())}
    for raw, family in document.families.items():
        view = views.get(raw)
        if family.verdict != "couple" or view is None:
            continue
        try:
            block = judged_va_block(
                pending.system,
                raw,
                {pending.system: pending.block},
                ctx.answers,
                devices=view.n_devices,
            )
        except KeyError:
            continue
        gap = missing_nominal(
            block, family.nominal_source or "Setpoint", family.kind, view.n_devices
        )
        if gap is not None:
            yield Problem(
                f"virtual_accelerator.families.{raw}.verdict",
                f"couples as {family.kind} and the export {gap}; "
                "a driven device starts the model somewhere",
            )


def _facility_token(ctx: _Context) -> Iterator[Problem]:
    token = ctx.mapping.facility.token
    if token is not None and not is_pn_local(token):
        yield Problem("facility.token", f"{token!r} is not a valid PN_LOCAL token")


def _unknown_systems(ctx: _Context) -> Iterator[Problem]:
    for raw in ctx.mapping.systems:
        if raw not in ctx.systems:
            yield Problem(f"systems.{raw}", "names a system absent from ao.json")
    for raw in ctx.systems:
        if raw not in ctx.mapping.systems:
            yield Problem(f"systems.{raw}", "ao.json system has no systems: entry")


def _unknown_families(ctx: _Context) -> Iterator[Problem]:
    for raw in ctx.mapping.families:
        if raw not in ctx.family_fields:
            yield Problem(f"families.{raw}", "names a family absent from ao.json")
    for raw in ctx.family_fields:
        if raw not in ctx.mapping.families:
            yield Problem(f"families.{raw}", "ao.json family has no families: entry")


def _renames(ctx: _Context) -> Iterator[Problem]:
    for raw, family in ctx.mapping.families.items():
        if family.rename is not None and not is_pn_local(family.rename):
            yield Problem(
                f"families.{raw}.rename", f"{family.rename!r} is not a valid PN_LOCAL token"
            )


def _branches_of_families(ctx: _Context) -> Iterator[Problem]:
    for raw, family in ctx.mapping.families.items():
        if family.branch is not None and not ctx.known_parent(family.branch):
            yield Problem(
                f"families.{raw}.branch",
                f"{family.branch!r} names neither a packaged class nor a declared branch",
            )


def _classes(ctx: _Context) -> Iterator[Problem]:
    for raw, family in ctx.mapping.families.items():
        klass = family.class_
        if klass is None:
            continue
        if klass == ROOT_CLASS:
            yield Problem(f"families.{raw}.class", f"must not be the root class {ROOT_CLASS!r}")
        elif not is_pn_local(klass):
            yield Problem(f"families.{raw}.class", f"{klass!r} is not a valid PN_LOCAL token")


def _packaged_class_branch(ctx: _Context) -> Iterator[Problem]:
    for raw, family in ctx.mapping.families.items():
        packaged = ctx.packaged.get(family.class_) if family.class_ is not None else None
        if packaged is not None and family.branch not in (None, packaged.parent):
            yield Problem(
                f"families.{raw}.branch",
                f"the packaged class {family.class_!r} has the parent {packaged.parent!r}, "
                f"not {family.branch!r}",
            )


def _shared_new_class(ctx: _Context) -> Iterator[Problem]:
    first: dict[str, tuple[str, str]] = {}
    for raw, family in ctx.mapping.families.items():
        klass, branch = family.class_, family.branch
        if klass is None or branch is None or klass in ctx.packaged or klass == ROOT_CLASS:
            continue
        seen = first.setdefault(klass, (raw, branch))
        if seen[1] != branch:
            yield Problem(
                f"families.{raw}.branch",
                f"the class {klass!r} already has the branch {seen[1]!r} "
                f"on the family {seen[0]!r}, not {branch!r}",
            )


def _missing_direction_groups(ctx: _Context) -> Iterator[Problem]:
    for family, fields in ctx.family_fields.items():
        for name in fields:
            key = f"{family}.{name}"
            if key not in ctx.mapping.directions:
                yield Problem(f"directions.{key}", "signal group has no directions entry")


def _system_names(ctx: _Context) -> Iterator[Problem]:
    folded: dict[str, str] = {}
    for raw, system in ctx.mapping.systems.items():
        if not is_pn_local(system.name):
            yield Problem(f"systems.{raw}.name", f"{system.name!r} is not a valid PN_LOCAL token")
        other = folded.setdefault(system.name.lower(), raw)
        if other != raw:
            yield Problem(
                f"systems.{raw}.name",
                f"{system.name!r} folds to the same lower-case name as systems.{other}",
            )


def _family_prefixes(ctx: _Context) -> Iterator[Problem]:
    folded: dict[str, str] = {}
    for raw in ctx.mapping.families:
        token = ctx.mapping.mapped(raw)
        other = folded.setdefault(token.lower().replace("-", "_"), raw)
        if other != raw:
            yield Problem(
                f"families.{raw}",
                f"mapped token {token!r} folds to the same signal prefix as families.{other}; "
                "set rename on one of them",
            )


def _declared_branches(ctx: _Context) -> Iterator[Problem]:
    branches = ctx.mapping.branches
    for name, branch in branches.items():
        if name == ROOT_CLASS or name in ctx.packaged:
            yield Problem(f"branches.{name}", "is named like a packaged class")
        if not ctx.known_parent(branch.parent):
            yield Problem(
                f"branches.{name}.parent",
                f"{branch.parent!r} names neither a packaged class nor a declared branch",
            )
    for name in branches:
        seen: set[str] = set()
        current = name
        while current in branches and current not in seen:
            seen.add(current)
            current = branches[current].parent
        if current == name:
            yield Problem(f"branches.{name}.parent", "forms a cycle of declared branches")


def _section_order(ctx: _Context) -> Iterator[Problem]:
    names = [system.name for system in ctx.mapping.systems.values()]
    seen: set[str] = set()
    for index, name in enumerate(ctx.mapping.section_order):
        if name not in names:
            yield Problem(f"section_order[{index}]", f"{name!r} is not a system name")
        elif name in seen:
            yield Problem(f"section_order[{index}]", f"{name!r} appears more than once")
        seen.add(name)
    missing = [name for name in names if name not in seen]
    if missing:
        yield Problem("section_order", f"is missing the system names {missing!r}")


def _direction_keys(ctx: _Context) -> Iterator[Problem]:
    for key in ctx.mapping.directions:
        family, _, name = key.partition(".")
        if family not in ctx.mapping.families:
            yield Problem(f"directions.{key}", f"names the family {family!r} absent from families:")
        elif name not in ctx.family_fields.get(family, {}):
            yield Problem(
                f"directions.{key}", f"names the field {name!r} absent from {family!r} in ao.json"
            )


def _stated_against_vote(ctx: _Context) -> Iterator[Problem]:
    for key, direction in ctx.mapping.directions.items():
        if direction.provenance != STATED or direction.direction is None or direction.override:
            continue
        family, _, name = key.partition(".")
        vote = ctx.votes.get((family, name))
        if (
            vote is not None
            and vote.direction is not None
            and vote.direction != direction.direction
        ):
            yield Problem(
                f"directions.{key}",
                f"stated {direction.direction!r} disagrees with the vote {vote.direction!r}; "
                "set override: true to keep it",
            )


_PREDICATES: tuple[Predicate, ...] = (
    _null_domain,
    _judgments,
    _va_values,
    _virtual_accelerator,
    _facility_token,
    _unknown_systems,
    _unknown_families,
    _renames,
    _branches_of_families,
    _classes,
    _packaged_class_branch,
    _shared_new_class,
    _missing_direction_groups,
    _system_names,
    _family_prefixes,
    _declared_branches,
    _section_order,
    _direction_keys,
    _stated_against_vote,
)


def _level(key: str) -> str:
    """Return the description level of a provenance slot key."""
    if key == "facility":
        return "facility"
    if key.startswith("systems."):
        return "system"
    return "field" if ".fields." in key else "family"


def check_mapping(
    mapping: Mapping,
    ao: dict,
    votes: dict[tuple[str, str], Vote],
    *,
    no_derived: bool,
    va: VAExport | None = None,
) -> CheckResult:
    """Check a parsed mapping against the merged export it maps.

    Args:
        mapping: The structurally valid mapping.
        ao: ``{system: {family: body}}``; keys starting with ``_`` and
            non-dict bodies are skipped. Not modified.
        votes: :func:`~osprey.services.mml.directions.vote_directions` of ``ao``.
        no_derived: Report every ``derived`` provenance slot as a problem.
        va: The virtual accelerator the tree carries, or ``None`` on a tree
            whose export states none -- where the ``virtual_accelerator`` block
            is neither asked for nor judged, only read for its null slots.

    Returns:
        Every problem found and the derived counts.
    """
    ctx = _Context(mapping, ao, votes, va)
    problems = [problem for predicate in _PREDICATES for problem in predicate(ctx)]

    descriptions = dict.fromkeys(_LEVELS, 0)
    directions = 0
    derived_keys: list[str] = []
    for key, provenance in mapping.provenance_slots():
        if provenance != DERIVED:
            continue
        derived_keys.append(key)
        if key.startswith("directions."):
            directions += 1
        else:
            descriptions[_level(key)] += 1
    if no_derived:
        problems.extend(
            Problem(f"{key}.provenance", "is derived; review it and mark it stated")
            for key in derived_keys
        )
    return CheckResult(
        problems=problems, derived_descriptions=descriptions, derived_directions=directions
    )
