# Generated by `gen-pydantic core.yaml` (linkml 1.11.1), run from
# src/osprey/facility/schema/; everything below these three lines is its
# stdout, byte for byte. Edit core.yaml or vocabulary.yaml, never this file.
from __future__ import annotations

import re
import sys
from datetime import (
    date,
    datetime,
    time
)
from decimal import Decimal
from enum import Enum
from typing import (
    Any,
    ClassVar,
    Literal,
    Optional,
    Union
)

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SerializationInfo,
    SerializerFunctionWrapHandler,
    field_validator,
    model_serializer
)


metamodel_version = "1.11.0"
version = "None"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        serialize_by_alias = True,
        validate_by_name = True,
        validate_assignment = True,
        validate_default = True,
        extra = "forbid",
        arbitrary_types_allowed = True,
        use_enum_values = True,
        strict = False,
    )





class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key:str):
        return getattr(self.root, key)

    def __getitem__(self, key:str):
        return self.root[key]

    def __setitem__(self, key:str, value):
        self.root[key] = value

    def __contains__(self, key:str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta({'default_prefix': 'osprey_facility',
     'default_range': 'string',
     'description': 'One facility, described once: its places, devices, channels '
                    'and groups, the models that simulate it and how each model is '
                    'wired to channels, the write limits and the scenarios. '
                    '`osprey build` combines the sources under data/facility/ into '
                    'one file of this shape. Every list whose order carries '
                    'meaning sets `list_elements_ordered`; a multivalued slot '
                    'without it is a set, compared and written sorted by its '
                    'string form.',
     'id': 'https://narad.example.org/schema/osprey.facility.core',
     'imports': ['linkml:types', 'vocabulary'],
     'name': 'osprey.facility.core',
     'prefixes': {'linkml': {'prefix_prefix': 'linkml',
                             'prefix_reference': 'https://w3id.org/linkml/'},
                  'osprey_facility': {'prefix_prefix': 'osprey_facility',
                                      'prefix_reference': 'https://narad.example.org/schema/osprey.facility.core/'}},
     'source_file': 'core.yaml',
     'title': 'Facility file'} )

class SignalRoleEnum(str, Enum):
    """
    Signal roles with a meaning shared across facilities; a channel's `signal` names one of them.
    """
    current_setpoint = "current_setpoint"
    """
    Commanded current value sent to a powered device.
    """
    current_readback = "current_readback"
    """
    Measured current value read back from a powered device.
    """
    field_setpoint = "field_setpoint"
    """
    Commanded field (integrated or peak) for a magnetic device.
    """
    field_readback = "field_readback"
    """
    Measured field readback for a magnetic device.
    """
    vacuum_readback = "vacuum_readback"
    """
    Vacuum pressure readback from a vacuum gauge or pump.
    """
    status = "status"
    """
    Generic device status (on/off/fault/enabled/disabled).
    """
    position_x_readback = "position_x_readback"
    """
    Horizontal beam position readback from a beam position monitor.
    """
    position_y_readback = "position_y_readback"
    """
    Vertical beam position readback from a beam position monitor.
    """
    beam_intensity_readback = "beam_intensity_readback"
    """
    Scalar beam intensity or charge readback (e.g. BPM .VAL).
    """
    profile_readback = "profile_readback"
    """
    Beam profile readback from a wire scanner or harp.
    """
    rf_forward_power_readback = "rf_forward_power_readback"
    """
    RF forward power readback at an accelerating cavity input.
    """
    rf_reflected_power_readback = "rf_reflected_power_readback"
    """
    RF reflected power readback from an accelerating cavity.
    """
    gradient_readback = "gradient_readback"
    """
    Measured accelerating gradient readback for an RF cavity.
    """
    gradient_setpoint = "gradient_setpoint"
    """
    Commanded accelerating gradient setpoint for an RF cavity.
    """
    phase_readback = "phase_readback"
    """
    Measured RF phase readback for an RF cavity.
    """
    phase_setpoint = "phase_setpoint"
    """
    Commanded RF phase setpoint for an RF cavity.
    """
    magnet_voltage_readback = "magnet_voltage_readback"
    """
    Voltage readback across a magnet or its driver supply (e.g. a D.H suffix on dipoles and correctors).
    """
    valve_status = "valve_status"
    """
    Open/closed/fault status readback for a beamline gate valve or fast valve.
    """
    integrated_count = "integrated_count"
    """
    Integrated beam-loss count readback from a beam loss monitor (BLM).
    """
    gun_voltage_setpoint = "gun_voltage_setpoint"
    """
    High-voltage setpoint for an electron gun or its HVPS (preset demand, kV).
    """
    gun_voltage_readback = "gun_voltage_readback"
    """
    High-voltage readback from an electron gun HVPS (measured kV).
    """
    gun_current_readback = "gun_current_readback"
    """
    Beam current or supply current readback from an electron gun HVPS (mA).
    """
    sf6_pressure_readback = "sf6_pressure_readback"
    """
    SF6 insulating-gas pressure readback in an electron gun pressure vessel (PSI).
    """
    current_golden_readback = "current_golden_readback"
    """
    Stored "golden" current setpoint reference for a powered device.
    """
    power_on_status = "power_on_status"
    """
    Power-on (energised) state readback of a powered device.
    """
    power_on_command = "power_on_command"
    """
    Commanded power on/off transition for a powered device.
    """
    ready_status = "ready_status"
    """
    Device-ready handshake readback (interlocks satisfied, supplies up).
    """
    fault_status = "fault_status"
    """
    Generic device fault flag readback.
    """
    reset_command = "reset_command"
    """
    Latching-fault reset command.
    """
    local_mode_status = "local_mode_status"
    """
    Local-vs-remote control-mode readback.
    """
    interlock_status = "interlock_status"
    """
    Generic interlock readback (active / cleared).
    """
    ramp_rate_setpoint = "ramp_rate_setpoint"
    """
    Commanded ramp-rate setpoint for a powered device's current loop.
    """
    ramping_status = "ramping_status"
    """
    Ramping-in-progress readback.
    """
    leakage_current_readback = "leakage_current_readback"
    """
    Leakage-current readback for a magnet supply.
    """
    regulator_temperature_readback = "regulator_temperature_readback"
    """
    Regulator / power-stage temperature readback.
    """
    bulk_supply_command = "bulk_supply_command"
    """
    Bulk-supply control command (mode/enable).
    """
    bulk_supply_on_status = "bulk_supply_on_status"
    """
    Bulk-supply on/off state readback.
    """
    bulk_supply_voltage_readback = "bulk_supply_voltage_readback"
    """
    Bulk-supply DC voltage readback.
    """
    controlled_power_mode_status = "controlled_power_mode_status"
    """
    Controlled-power-mode readback for a main dipole supply.
    """
    over_temperature_status = "over_temperature_status"
    """
    Over-temperature fault flag readback.
    """
    shunt_status = "shunt_status"
    """
    Dipole shunt-circuit state readback.
    """
    position_x_error_readback = "position_x_error_readback"
    """
    Horizontal-position error readback (delta from golden reference).
    """
    position_y_error_readback = "position_y_error_readback"
    """
    Vertical-position error readback (delta from golden reference).
    """
    position_x_golden_readback = "position_x_golden_readback"
    """
    Golden-orbit horizontal-position reference readback.
    """
    position_y_golden_readback = "position_y_golden_readback"
    """
    Golden-orbit vertical-position reference readback.
    """
    position_x_rms_10k_readback = "position_x_rms_10k_readback"
    """
    RMS horizontal position over a 10k-sample window.
    """
    position_y_rms_10k_readback = "position_y_rms_10k_readback"
    """
    RMS vertical position over a 10k-sample window.
    """
    position_x_rms_200_readback = "position_x_rms_200_readback"
    """
    RMS horizontal position over a 200-sample window.
    """
    position_y_rms_200_readback = "position_y_rms_200_readback"
    """
    RMS vertical position over a 200-sample window.
    """
    bpm_sum_readback = "bpm_sum_readback"
    """
    BPM sum-signal readback (intensity proxy from button electrodes).
    """
    bpm_fofb_index = "bpm_fofb_index"
    """
    Fast-orbit-feedback channel-index readback for a BPM.
    """
    bpm_sample_rate = "bpm_sample_rate"
    """
    BPM acquisition sample-rate readback (configuration channel).
    """
    rf_hv_readback = "rf_hv_readback"
    """
    RF / klystron high-voltage readback.
    """
    rf_hv_setpoint = "rf_hv_setpoint"
    """
    RF / klystron high-voltage setpoint.
    """
    rf_hv_golden_readback = "rf_hv_golden_readback"
    """
    Stored golden HV reference for an RF cavity.
    """
    rf_drive_amplitude_readback = "rf_drive_amplitude_readback"
    """
    RF drive-amplitude readback.
    """
    phase_golden_readback = "phase_golden_readback"
    """
    Stored golden RF-phase reference.
    """
    local_phase_readback = "local_phase_readback"
    """
    Locally-measured RF-phase readback.
    """
    remote_phase_readback = "remote_phase_readback"
    """
    Remotely-reported RF-phase readback.
    """
    thermal_status = "thermal_status"
    """
    Thermal/over-temperature interlock flag readback.
    """
    filament_timeout_status = "filament_timeout_status"
    """
    Filament warm-up / runtime timeout readback.
    """
    computer_status = "computer_status"
    """
    Control-computer heartbeat / health readback.
    """
    pulse_amplitude_setpoint = "pulse_amplitude_setpoint"
    """
    Modulator pulse-amplitude setpoint.
    """
    pulse_delay_setpoint = "pulse_delay_setpoint"
    """
    Modulator pulse-delay setpoint.
    """
    pulse_width_setpoint = "pulse_width_setpoint"
    """
    Modulator pulse-width setpoint.
    """
    pulse_permit_status = "pulse_permit_status"
    """
    Pulsing-permit interlock readback.
    """
    pulsing_command = "pulsing_command"
    """
    Commanded pulsing on/off transition.
    """
    pulsing_on_status = "pulsing_on_status"
    """
    Pulsing-on state readback.
    """
    pulsing_ready_status = "pulsing_ready_status"
    """
    Pulsing-ready handshake readback.
    """
    modulator_state_command = "modulator_state_command"
    """
    Modulator state-machine command (StateCmd; MemberOf=Boolean Control).
    """
    screen_in_status = "screen_in_status"
    """
    Screen-inserted state readback.
    """
    screen_out_status = "screen_out_status"
    """
    Screen-extracted state readback.
    """
    screen_in_command = "screen_in_command"
    """
    Commanded screen-insert transition.
    """
    lamp_status = "lamp_status"
    """
    Illumination-lamp on/off state readback.
    """
    lamp_command = "lamp_command"
    """
    Commanded lamp on/off transition.
    """
    valve_open_command = "valve_open_command"
    """
    Commanded valve open/close transition.
    """
    valve_upstream_status = "valve_upstream_status"
    """
    Upstream-side limit-switch state readback for a vacuum valve.
    """
    valve_downstream_status = "valve_downstream_status"
    """
    Downstream-side limit-switch state readback for a vacuum valve.
    """
    valve_cathode_status = "valve_cathode_status"
    """
    Cathode-side interlock / status channel for a vacuum valve.
    """
    air_pressure_status = "air_pressure_status"
    """
    Compressed-air-pressure (pneumatic actuator supply) readback.
    """
    ac_supply_ok_status = "ac_supply_ok_status"
    """
    AC-supply OK readback (120 V auxiliary supply healthy).
    """
    dc_supply_ok_status = "dc_supply_ok_status"
    """
    DC-supply OK readback (24 V auxiliary supply healthy).
    """
    plug_interlock_status = "plug_interlock_status"
    """
    Plug-interlock readback (mating-connector presence).
    """
    external_interlock_1_status = "external_interlock_1_status"
    """
    External interlock channel 1 readback.
    """
    external_interlock_2_status = "external_interlock_2_status"
    """
    External interlock channel 2 readback.
    """
    external_interlock_3_status = "external_interlock_3_status"
    """
    External interlock channel 3 readback.
    """
    internal_interlock_1_status = "internal_interlock_1_status"
    """
    Internal interlock channel 1 readback.
    """
    internal_interlock_2_status = "internal_interlock_2_status"
    """
    Internal interlock channel 2 readback.
    """
    internal_interlock_3_status = "internal_interlock_3_status"
    """
    Internal interlock channel 3 readback.
    """


class PropertyNameEnum(str, Enum):
    """
    Property names a device record lists in `properties`, each with the unit its value carries.
    """
    betax = "betax"
    """
    Horizontal beta function from the accelerator optics model.
    """
    betay = "betay"
    """
    Vertical beta function from the accelerator optics model.
    """
    alphax = "alphax"
    """
    Horizontal alpha (Twiss parameter) from the optics model.
    """
    alphay = "alphay"
    """
    Vertical alpha (Twiss parameter) from the optics model.
    """
    etax = "etax"
    """
    Horizontal dispersion function from the optics model.
    """
    etay = "etay"
    """
    Vertical dispersion function from the optics model.
    """
    psix = "psix"
    """
    Horizontal betatron phase advance.
    """
    psiy = "psiy"
    """
    Vertical betatron phase advance.
    """
    emitx = "emitx"
    """
    Horizontal normalised emittance.
    """
    emity = "emity"
    """
    Vertical normalised emittance.
    """
    pCentral = "pCentral"
    """
    Central (design) beam momentum from the optics model.
    """
    sigmax = "sigmax"
    """
    Horizontal beam-envelope RMS size from the optics model.
    """
    sigmay = "sigmay"
    """
    Vertical beam-envelope RMS size from the optics model.
    """
    s_position = "s_position"
    """
    Longitudinal position along the beamline (s-coordinate).
    """
    length = "length"
    """
    Physical length of the device element.
    """


class RoleEnum(str, Enum):
    """
    What a program does with a channel.
    """
    setpoint = "setpoint"
    """
    Written by a program; read back through its `pair`.
    """
    readback = "readback"
    """
    Read only; the pair of at most one setpoint.
    """
    none = "none"
    """
    Neither written nor paired.
    """


class ValueTypeEnum(str, Enum):
    """
    The type of the value a channel carries.
    """
    float = "float"
    int = "int"
    bool = "bool"
    enum = "enum"
    string = "string"
    waveform = "waveform"


class EnergyScalingEnum(str, Enum):
    """
    How a calibration scales with the reference energy.
    """
    none = "none"
    brho = "brho"


class PlaceFromEnum(str, Enum):
    """
    Where a device's `place` came from.
    """
    span = "span"
    """
    No source stated one; the deepest span containing the device's s.
    """
    authored = "authored"
    """
    Stated in an authored record.
    """
    fix = "fix"
    """
    Set by a fix.
    """


class FixOpEnum(str, Enum):
    set = "set"
    add = "add"
    drop = "drop"


class MeasurementKindEnum(str, Enum):
    """
    The measurements a model's measurement file allows.
    """
    orm = "orm"
    dispersion = "dispersion"
    trm = "trm"
    crm = "crm"
    chromaticity_monitor = "chromaticity_monitor"



class AcceleratorDevice(ConfiguredBaseModel):
    """
    Abstract root for all accelerator devices.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Instrumentation(AcceleratorDevice):
    """
    Abstract root for instrumentation and diagnostic devices.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'aliases': ['instrumentation', 'diagnostics'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Actuated(Instrumentation):
    """
    Instrumentation devices with mechanically actuated or insertable elements.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'aliases': ['actuated', 'insertable'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Magnet(AcceleratorDevice):
    """
    A device whose primary function is magnetic beam steering or focusing.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'aliases': ['magnet', 'electromagnet'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Dipole(Magnet):
    """
    Dipole bending magnet.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['dipole',
                     'bending magnet',
                     'bend magnet',
                     'bend',
                     'dipole magnet'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Corrector(Magnet):
    """
    Orbit corrector magnet (horizontal or vertical).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'aliases': ['corrector', 'steerer', 'steering magnet', 'orbit corrector'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class HCorrector(Corrector):
    """
    Horizontal orbit corrector.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['horizontal corrector',
                     'HCorrector',
                     'HCOR',
                     'horizontal orbit corrector',
                     'horizontal steering magnet'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class VCorrector(Corrector):
    """
    Vertical orbit corrector.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['vertical corrector',
                     'VCorrector',
                     'VCOR',
                     'vertical orbit corrector',
                     'vertical steering magnet'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Solenoid(Magnet):
    """
    Solenoid focusing magnet.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['solenoid', 'solenoid magnet', 'axial focusing magnet'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Sextupole(Magnet):
    """
    Sextupole magnet used for chromatic correction and higher-order optics control.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['sextupole', 'sext'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Octupole(Magnet):
    """
    Octupole magnet used for nonlinear optics shaping and stability control.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['octupole'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class WienFilter(Magnet):
    """
    Crossed-field Wien filter used for velocity and spin manipulation with minimal orbit distortion.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['wien filter', 'wien'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Vacuum(AcceleratorDevice):
    """
    Abstract root for vacuum systems and instrumentation.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'aliases': ['vacuum'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Pump(Vacuum):
    """
    Vacuum pump (ion pump, NEG pump, etc.).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['pump', 'ion pump', 'vacuum pump'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Valve(Vacuum):
    """
    Beamline gate valve or isolation valve.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['valve',
                     'beamline valve',
                     'gate valve',
                     'isolation valve',
                     'fast valve',
                     'BV',
                     'FV'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Quadrupole(Magnet):
    """
    Quadrupole focusing or defocusing magnet.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['quadrupole',
                     'quad',
                     'focusing magnet',
                     'defocusing magnet',
                     'quadrupole magnet'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class RadioFrequency(AcceleratorDevice):
    """
    Abstract root for RF acceleration structures.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'aliases': ['radio frequency', 'radiofrequency', 'RF'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class AcceleratingCavity(RadioFrequency):
    """
    RF accelerating cavity structure.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'aliases': ['accelerating cavity', 'RF cavity', 'cavity'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class NormalConducting(AcceleratingCavity):
    """
    Normal-conducting (warm) accelerating RF cavity structure.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['normal conducting', 'warm RF', 'warm'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Superconducting(AcceleratingCavity):
    """
    Superconducting RF structures.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['superconducting', 'SRF', 'cold', 'cryo'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class BeamPositionMonitor(Instrumentation):
    """
    Non-intercepting beam position monitor (stripline, cavity BPM, etc.).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['beam position monitor',
                     'position monitor',
                     'BPM',
                     'PM',
                     'position pickup'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class ScreenDiagnostic(Actuated):
    """
    Intercepting screen diagnostic (YAG screen, OTR, etc.).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['screen', 'viewer', 'profile screen'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class WireScanner(Actuated):
    """
    Beam profile wire scanner or harp.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['wire scanner',
                     'harp',
                     'wire harp',
                     'profile monitor',
                     'beam harp'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class FaradayCup(Actuated):
    """
    Insertable Faraday cup used for beam current interception and measurement.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['faraday cup', 'cup', 'faraday'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Aperture(Actuated):
    """
    Insertable aperture/collimator element used to constrain beam envelope and scrape halo.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['aperture', 'collimator', 'scraper'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Dump(Actuated):
    """
    Beam dump element used to absorb beam under controlled operating conditions.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['dump', 'beam dump'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Target(Instrumentation):
    """
    Beam-intercepting target element used for dedicated measurement or interaction stations.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['target'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class BunchLengthMonitor(Instrumentation):
    """
    Instrumentation for bunch-length related observation and monitoring.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['bunch length monitor', 'bunch monitor'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class BeamLossMonitor(Instrumentation):
    """
    Beam loss monitor (BLM) for machine protection and tuning.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['beam loss monitor', 'loss monitor', 'BLM', 'LM'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class BeamCurrentMonitor(Instrumentation):
    """
    Beam current monitor (BCM) for non-intercepting beam intensity readback.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['beam current monitor', 'current monitor', 'BCM', 'BC'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Gauge(Vacuum):
    """
    Vacuum pressure gauge (cold cathode, Pirani, ionisation gauge, etc.).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['gauge', 'vacuum gauge', 'pressure gauge'],
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class ElectronGun(AcceleratorDevice):
    """
    DC electron gun with high-voltage power supply (HVPS). Produces the primary beam; includes the gun electrode, HVPS, and SF6-insulated pressure vessel.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class AuxiliaryCoil(Magnet):
    """
    Abstract root for magnets whose purpose is field correction or cancellation rather than primary beam steering / focusing (e.g. bucking coils that null a solenoid's fringe field at the cathode).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class BuckingCoil(AuxiliaryCoil):
    """
    Field-cancellation coil pair used to null a parent magnet's fringe field (typically at the gun cathode).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Modulator(RadioFrequency):
    """
    High-power klystron / RF-driver modulator providing pulsed DC to an RF amplifier chain.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class BunchingCavity(RadioFrequency):
    """
    Abstract root for RF cavities whose primary function is longitudinal bunching rather than acceleration.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'abstract': True,
         'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class SubHarmonicBuncher(BunchingCavity):
    """
    Sub-harmonic buncher cavity operated below the linac fundamental frequency to compress bunches before injection.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class TravellingWaveCavity(AcceleratingCavity):
    """
    Travelling-wave RF accelerating structure (sibling to NormalConducting / Superconducting standing-wave cavities).
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class TimingChannel(Instrumentation):
    """
    Programmable event-timing channel (trigger, delay) sourced from the event-distribution system.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class TimingReference(Instrumentation):
    """
    Master phase / timing reference distributed to downstream timing channels.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.vocabulary'})

    pass


class Facility(ConfiguredBaseModel):
    """
    The whole facility file.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core',
         'tree_root': True})

    schema: str = Field(default=..., description="""The file header, `osprey.facility.<doc>/<version>`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Facility']} })
    identity: Identity = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Facility']} })
    classes: Optional[list[FacilityClass]] = Field(default=None, description="""The facility-added device classes, carried verbatim.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Facility'], 'list_elements_ordered': True} })
    places: Optional[list[Place]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Facility'], 'list_elements_ordered': True} })
    devices: Optional[list[Device]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Facility'], 'list_elements_ordered': True} })
    channels: Optional[list[Channel]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Facility'], 'list_elements_ordered': True} })
    groups: Optional[list[Group]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Facility', 'Device', 'Measurement'],
         'list_elements_ordered': True} })
    models: Optional[list[Model]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Facility'], 'list_elements_ordered': True} })
    limits: Optional[Limits] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Facility']} })
    scenarios: Optional[list[Scenario]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Facility'], 'list_elements_ordered': True} })

    @field_validator('schema')
    def pattern_schema(cls, v):
        pattern=re.compile(r"^osprey\.facility\.[a-z_]+/[0-9]+$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid schema format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid schema format: {v}"
            raise ValueError(err_msg)
        return v


class Identity(ConfiguredBaseModel):
    """
    Who the facility is.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    code: str = Field(default=..., description="""Names IRIs, status channels and the graph token.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Identity']} })
    name: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Identity', 'Model', 'Scenario']} })
    description: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Identity',
                       'FacilityClass',
                       'Place',
                       'Device',
                       'Channel',
                       'Group']} })

    @field_validator('code')
    def pattern_code(cls, v):
        pattern=re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid code format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid code format: {v}"
            raise ValueError(err_msg)
        return v


class FacilityClass(ConfiguredBaseModel):
    """
    A device class a facility adds as the child of an existing class.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    class_: str = Field(default=..., alias="class", json_schema_extra = { "linkml_meta": {'domain_of': ['FacilityClass', 'Device']} })
    parent: str = Field(default=..., description="""A vocabulary class or an earlier facility-added class.""", json_schema_extra = { "linkml_meta": {'domain_of': ['FacilityClass']} })
    aliases: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['FacilityClass'], 'list_elements_ordered': True} })
    description: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Identity',
                       'FacilityClass',
                       'Place',
                       'Device',
                       'Channel',
                       'Group']} })


class Provenance(ConfiguredBaseModel):
    """
    Which sources, fixes and defaults produced a record.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    sources: Optional[list[ProvenanceSource]] = Field(default=None, description="""One entry per layer that stated a field, sorted by layer.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Provenance'], 'list_elements_ordered': True} })
    fixes: Optional[list[ProvenanceFix]] = Field(default=None, description="""The fixes applied to the record, in fixes.yaml order.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Provenance'], 'list_elements_ordered': True} })
    defaults: Optional[list[str]] = Field(default=None, description="""The fields the build filled because no source stated them.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Provenance', 'Limits'], 'list_elements_ordered': True} })
    place_from: Optional[PlaceFromEnum] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Provenance']} })


class ProvenanceSource(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    layer: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['ProvenanceSource']} })
    file: str = Field(default=..., description="""Relative to data/facility/.""", json_schema_extra = { "linkml_meta": {'domain_of': ['ProvenanceSource']} })
    fields: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['ProvenanceSource'], 'list_elements_ordered': True} })


class ProvenanceFix(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    op: FixOpEnum = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['ProvenanceFix']} })
    why: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['ProvenanceFix']} })


class Place(ConfiguredBaseModel):
    """
    A node of the facility's own tree; its id is a `/`-separated path.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    id: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Wiring']} })
    level: Optional[str] = Field(default=None, description="""The facility's word for this depth of its tree.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Place']} })
    description: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Identity',
                       'FacilityClass',
                       'Place',
                       'Device',
                       'Channel',
                       'Group']} })
    names: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group'],
         'list_elements_ordered': True} })
    attributes: Optional[Any] = Field(default=None, description="""A free string to scalar or list map, carried verbatim.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel']} })
    span: Optional[Span] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place']} })
    provenance: Optional[Provenance] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Model', 'Wiring']} })


class Span(ConfiguredBaseModel):
    """
    The half-open stretch [from_marker, to_marker) of one model's deck that places devices; no `to_marker` means the end of the deck.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    model: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Span', 'Device']} })
    from_marker: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Span']} })
    to_marker: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Span']} })


class Device(ConfiguredBaseModel):
    """
    One device; its channels point at it through `on`.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    id: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Wiring']} })
    class_: Optional[str] = Field(default=None, alias="class", description="""A vocabulary class or a facility-added class.""", json_schema_extra = { "linkml_meta": {'domain_of': ['FacilityClass', 'Device']} })
    place: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Device', 'OnTarget']} })
    description: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Identity',
                       'FacilityClass',
                       'Place',
                       'Device',
                       'Channel',
                       'Group']} })
    names: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group'],
         'list_elements_ordered': True} })
    properties: Optional[list[str]] = Field(default=None, description="""Vocabulary property names.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Device'], 'list_elements_ordered': True} })
    attributes: Optional[Any] = Field(default=None, description="""A free string to scalar or list map, carried verbatim.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel']} })
    model: Optional[str] = Field(default=None, description="""Computed; the model whose deck gave `s` and `length`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Span', 'Device']} })
    s: Optional[float] = Field(default=None, description="""Computed; the entrance of the device's wired elements, in metres.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Device']} })
    length: Optional[float] = Field(default=None, description="""Computed; in metres.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Device']} })
    ordinalInPlace: Optional[int] = Field(default=None, description="""Computed; the device's ordinal among its class in its place.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Device']} })
    ordinalInModel: Optional[int] = Field(default=None, description="""Computed; the device's ordinal among its class in its model.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Device']} })
    groups: Optional[list[str]] = Field(default=None, description="""Computed; the groups naming the device as a member.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Facility', 'Device', 'Measurement']} })
    provenance: Optional[Provenance] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Model', 'Wiring']} })


class OnTarget(ConfiguredBaseModel):
    """
    The one device or place a channel belongs to.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    device: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['OnTarget', 'Slice']} })
    place: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Device', 'OnTarget']} })


class Channel(ConfiguredBaseModel):
    """
    One control-system channel; its id is the full address.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    id: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Wiring']} })
    role: Optional[RoleEnum] = Field(default=None, description="""Absent means readback.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    pair: Optional[str] = Field(default=None, description="""The readback address of a setpoint; absent means the setpoint itself.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    on: Optional[OnTarget] = Field(default=None, description="""Absent means the channel belongs to nothing.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    endpoint_of: Optional[list[str]] = Field(default=None, description="""The devices sharing this channel as an endpoint.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    signal: Optional[str] = Field(default=None, description="""A vocabulary signal role.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    unit: Optional[str] = Field(default=None, description="""Free text.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel', 'Wiring']} })
    description: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Identity',
                       'FacilityClass',
                       'Place',
                       'Device',
                       'Channel',
                       'Group']} })
    names: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group'],
         'list_elements_ordered': True} })
    former_addresses: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    tags: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    attributes: Optional[Any] = Field(default=None, description="""A free string to scalar or list map, carried verbatim.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel']} })
    value_type: Optional[ValueTypeEnum] = Field(default=None, description="""Absent means float.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    options: Optional[list[str]] = Field(default=None, description="""The labels of a bool or enum channel.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel'], 'list_elements_ordered': True} })
    shape: Optional[list[int]] = Field(default=None, description="""The dimensions of a waveform channel.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel'], 'list_elements_ordered': True} })
    simulation: Optional[Seed] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Channel']} })
    provenance: Optional[Provenance] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Model', 'Wiring']} })


class Seed(ConfiguredBaseModel):
    """
    How an unwired channel behaves when simulated.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    nominal: Optional[Any] = Field(default=None, description="""The value at start, of the channel's value_type.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Seed']} })
    noise: Optional[float] = Field(default=None, description="""Additive Gaussian sigma in the channel's unit.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Seed']} })
    drift: Optional[Drift] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Seed']} })
    clamp: Optional[list[Any]] = Field(default=None, description="""[low, high]; either side may be null.""", min_length=2, max_length=2, json_schema_extra = { "linkml_meta": {'domain_of': ['Seed'], 'list_elements_ordered': True} })
    linear: Optional[dict[str, Union[float, LinearTerm]]] = Field(default=None, description="""The value as a weighted sum of other channels, `{<address>: <coefficient>}`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Seed', 'Curve'], 'list_elements_ordered': True} })


class Drift(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    amplitude: float = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Drift']} })
    period_s: float = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Drift']} })


class LinearTerm(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    address: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['LinearTerm', 'Wiring', 'LimitRecord']} })
    coefficient: float = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['LinearTerm']} })


class Group(ConfiguredBaseModel):
    """
    A named set of devices.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    id: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Wiring']} })
    description: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Identity',
                       'FacilityClass',
                       'Place',
                       'Device',
                       'Channel',
                       'Group']} })
    names: Optional[list[str]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group'],
         'list_elements_ordered': True} })
    members: Optional[list[str]] = Field(default=None, description="""Device ids.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Group']} })
    signals: Optional[dict[str, Union[str, SignalSentence]]] = Field(default=None, description="""One sentence per kind of signal the members carry, `{<field or field/subfield>: <sentence>}`, carried verbatim.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Group'], 'list_elements_ordered': True} })
    provenance: Optional[Provenance] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Model', 'Wiring']} })


class SignalSentence(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    key: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['SignalSentence']} })
    sentence: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['SignalSentence']} })


class Model(ConfiguredBaseModel):
    """
    One simulation model and how it is wired to channels.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    name: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Identity', 'Model', 'Scenario']} })
    engine: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Model', 'Wiring']} })
    deck: Optional[str] = Field(default=None, description="""Relative to data/facility/.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Model']} })
    settings: Optional[Any] = Field(default=None, description="""`{<engine>: {...}}`, the one key equal to `engine`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Model']} })
    wiring: Optional[list[Wiring]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Model'], 'list_elements_ordered': True} })
    measurement: Optional[Measurement] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Model']} })
    provenance: Optional[Provenance] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Model', 'Wiring']} })

    @field_validator('name')
    def pattern_name(cls, v):
        pattern=re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
        if isinstance(v, list):
            for element in v:
                if isinstance(element, str) and not pattern.match(element):
                    err_msg = f"Invalid name format: {element}"
                    raise ValueError(err_msg)
        elif isinstance(v, str) and not pattern.match(v):
            err_msg = f"Invalid name format: {v}"
            raise ValueError(err_msg)
        return v


class Wiring(ConfiguredBaseModel):
    """
    One model variable: a channel's address driven by or read from `element` or `slices`, never both.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    id: str = Field(default=..., description="""`<model>/<address>`, split at the first `/`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Wiring']} })
    address: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['LinearTerm', 'Wiring', 'LimitRecord']} })
    element: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Wiring', 'Slice']} })
    slices: Optional[list[Slice]] = Field(default=None, description="""The first slice is the element read from.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Wiring'], 'list_elements_ordered': True} })
    engine: Optional[Any] = Field(default=None, description="""The engine's own words for the variable.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Model', 'Wiring']} })
    calibration: Optional[Calibration] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Wiring']} })
    direction: Optional[str] = Field(default=None, description="""Computed from the channel's role.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Wiring']} })
    unit: Optional[str] = Field(default=None, description="""Computed from the channel.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Channel', 'Wiring']} })
    default: Optional[Any] = Field(default=None, description="""Computed; the operating point from the deck.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Wiring']} })
    value_range: Optional[list[float]] = Field(default=None, description="""Computed from the channel's limits record.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Wiring'], 'list_elements_ordered': True} })
    provenance: Optional[Provenance] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Place', 'Device', 'Channel', 'Group', 'Model', 'Wiring']} })


class Slice(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    element: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Wiring', 'Slice']} })
    weight: Optional[float] = Field(default=None, description="""Absent means 1.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Slice']} })
    device: Optional[str] = Field(default=None, description="""Absent means the channel's device.""", json_schema_extra = { "linkml_meta": {'domain_of': ['OnTarget', 'Slice']} })


class Calibration(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    curve: Curve = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Calibration']} })
    inverse: Optional[Curve] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Calibration']} })
    energy_scaling: Optional[EnergyScalingEnum] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Calibration']} })


class Curve(ConfiguredBaseModel):
    """
    Exactly one of `linear` or `table`.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    linear: Optional[LinearCurve] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Seed', 'Curve']} })
    table: Optional[TableCurve] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Curve']} })


class LinearCurve(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    gain: float = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['LinearCurve']} })
    offset: float = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['LinearCurve']} })


class TableCurve(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    grid: list[float] = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['TableCurve'], 'list_elements_ordered': True} })
    values: list[float] = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['TableCurve'], 'list_elements_ordered': True} })


class Measurement(ConfiguredBaseModel):
    """
    The measurements a model allows and the groups and channels they use. The step and settle keys are pyAML's own, carried verbatim.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    kinds: Optional[list[MeasurementKindEnum]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    groups: Optional[MeasurementGroups] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Facility', 'Device', 'Measurement']} })
    instruments: Optional[MeasurementInstruments] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    n_step: Optional[int] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    n_avg_meas: Optional[int] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    fit_order: Optional[int] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    singular_values: Optional[int] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    sleep_between_step: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    sleep_between_meas: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    corrector_delta: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    quad_delta: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    sextu_delta: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })
    frequency_delta: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Measurement']} })


class MeasurementGroups(ConfiguredBaseModel):
    """
    Group ids.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    bpm: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['MeasurementGroups']} })
    hcor: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['MeasurementGroups']} })
    vcor: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['MeasurementGroups']} })
    quad: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['MeasurementGroups']} })
    sext: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['MeasurementGroups']} })


class MeasurementInstruments(ConfiguredBaseModel):
    """
    Channel addresses.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    tune: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['MeasurementInstruments']} })
    chromaticity: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['MeasurementInstruments']} })
    rf: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['MeasurementInstruments']} })


class Limits(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    defaults: LimitDefaults = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Provenance', 'Limits']} })
    records: Optional[list[LimitRecord]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Limits'], 'list_elements_ordered': True} })


class LimitDefaults(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    writable: bool = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['LimitDefaults', 'LimitRecord']} })
    confirm: bool = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['LimitDefaults', 'LimitRecord']} })


class LimitRecord(ConfiguredBaseModel):
    """
    The write limits of one channel.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    address: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['LinearTerm', 'Wiring', 'LimitRecord']} })
    min_value: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['LimitRecord']} })
    max_value: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['LimitRecord']} })
    max_step: Optional[float] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['LimitRecord']} })
    writable: Optional[bool] = Field(default=None, description="""Absent means `defaults.writable`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['LimitDefaults', 'LimitRecord']} })
    confirm: Optional[bool] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['LimitDefaults', 'LimitRecord']} })


class Scenario(ConfiguredBaseModel):
    """
    Values written into the models at start, and the narratives that go with them.
    """
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'https://narad.example.org/schema/osprey.facility.core'})

    name: str = Field(default=..., json_schema_extra = { "linkml_meta": {'domain_of': ['Identity', 'Model', 'Scenario']} })
    overrides: Optional[Any] = Field(default=None, description="""`{<address>: <value>}`, each value of the channel's value_type.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Scenario']} })
    faults: Optional[Any] = Field(default=None, description="""`{<model>: {<address or engine variable>: <value>}}`, where a value is a scalar, the word `stuck`, or a map `{<fault field>: <value>}`.""", json_schema_extra = { "linkml_meta": {'domain_of': ['Scenario']} })
    archiver: Optional[list[Any]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Scenario'], 'list_elements_ordered': True} })
    logbook: Optional[list[Any]] = Field(default=None, json_schema_extra = { "linkml_meta": {'domain_of': ['Scenario'], 'list_elements_ordered': True} })


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
AcceleratorDevice.model_rebuild()
Instrumentation.model_rebuild()
Actuated.model_rebuild()
Magnet.model_rebuild()
Dipole.model_rebuild()
Corrector.model_rebuild()
HCorrector.model_rebuild()
VCorrector.model_rebuild()
Solenoid.model_rebuild()
Sextupole.model_rebuild()
Octupole.model_rebuild()
WienFilter.model_rebuild()
Vacuum.model_rebuild()
Pump.model_rebuild()
Valve.model_rebuild()
Quadrupole.model_rebuild()
RadioFrequency.model_rebuild()
AcceleratingCavity.model_rebuild()
NormalConducting.model_rebuild()
Superconducting.model_rebuild()
BeamPositionMonitor.model_rebuild()
ScreenDiagnostic.model_rebuild()
WireScanner.model_rebuild()
FaradayCup.model_rebuild()
Aperture.model_rebuild()
Dump.model_rebuild()
Target.model_rebuild()
BunchLengthMonitor.model_rebuild()
BeamLossMonitor.model_rebuild()
BeamCurrentMonitor.model_rebuild()
Gauge.model_rebuild()
ElectronGun.model_rebuild()
AuxiliaryCoil.model_rebuild()
BuckingCoil.model_rebuild()
Modulator.model_rebuild()
BunchingCavity.model_rebuild()
SubHarmonicBuncher.model_rebuild()
TravellingWaveCavity.model_rebuild()
TimingChannel.model_rebuild()
TimingReference.model_rebuild()
Facility.model_rebuild()
Identity.model_rebuild()
FacilityClass.model_rebuild()
Provenance.model_rebuild()
ProvenanceSource.model_rebuild()
ProvenanceFix.model_rebuild()
Place.model_rebuild()
Span.model_rebuild()
Device.model_rebuild()
OnTarget.model_rebuild()
Channel.model_rebuild()
Seed.model_rebuild()
Drift.model_rebuild()
LinearTerm.model_rebuild()
Group.model_rebuild()
SignalSentence.model_rebuild()
Model.model_rebuild()
Wiring.model_rebuild()
Slice.model_rebuild()
Calibration.model_rebuild()
Curve.model_rebuild()
LinearCurve.model_rebuild()
TableCurve.model_rebuild()
Measurement.model_rebuild()
MeasurementGroups.model_rebuild()
MeasurementInstruments.model_rebuild()
Limits.model_rebuild()
LimitDefaults.model_rebuild()
LimitRecord.model_rebuild()
Scenario.model_rebuild()
