"""
Middle Layer Database Implementation

Implements MATLAB Middle Layer (MML) style organization for channel databases.
This approach organizes channels by functional hierarchy (System → Family → Field)
rather than by naming patterns, mirroring production accelerator control systems.

The database structure follows:
- Systems: Top-level accelerator systems (SR, BR, BTS, etc.)
- Families: Device families within systems (BPM, HCM, VCM, etc.)
- Fields: Functional fields within families (Monitor, Setpoint, etc.)
- Subfields: Optional nested fields for complex data structures
- ChannelNames: Actual EPICS PV addresses

Example structure:
{
  "SR": {
    "BPM": {
      "Monitor": {
        "ChannelNames": ["SR01C:BPM1:X", "SR01C:BPM1:Y", ...]
      },
      "Setpoint": {
        "X": {
          "ChannelNames": ["SR01C:BPM1:XSet", ...]
        },
        "Y": {
          "ChannelNames": ["SR01C:BPM1:YSet", ...]
        }
      },
      "setup": {
        "CommonNames": ["BPM 1", "BPM 2", ...],
        "DeviceList": [[1, 1], [1, 2], ...]  # [sector, device] pairs
      }
    }
  }
}
"""

import json
from typing import Any

from ..core.base_database import BaseDatabase

#: Keys under which a middle-layer field lists its channel addresses, in the
#: order readers consult them. ``ChannelNames`` holds Channel Access names and
#: ``TangoNames`` Tango device attributes; a field may carry either or both.
CHANNEL_KEYS: tuple[str, ...] = ("ChannelNames", "TangoNames")

#: Top-level keys of an index that name the document, not a system.
DOCUMENT_KEYS = frozenset({"schema"})

# Metadata keys to skip during tree traversal (not navigable families/fields)
_ML_META_KEYS = frozenset(
    {
        "_description",
        "_setup",
        "setup",
        "pyat",
        *CHANNEL_KEYS,
        "DataType",
        "Mode",
        "Units",
        "HW2PhysicsParams",
        "Physics2HWParams",
        "Tol",
        "Range",
        "Description",
        "CommonNames",
        "DeviceList",
    }
)


def get_setup(family_data: dict) -> dict:
    """Return the setup block from a family node.

    Checks for both ``"setup"`` (legacy MML exports) and ``"_setup"``
    (generated by the benchmark generator) keys.

    Args:
        family_data: The family-level dict from the MML tree.

    Returns:
        The setup dict, or an empty dict if neither key is present.
    """
    return family_data.get("setup") or family_data.get("_setup") or {}


def _add_membership(channels: dict[str, dict], name: str, membership: dict[str, Any]) -> None:
    """File one listing of ``name`` among its channel entry's memberships.

    A channel entry holds one membership per (System, Family) that lists the
    channel, in document order. A family that lists the channel under several
    fields keeps the last of them in that family's place.
    """
    entry = channels.setdefault(name, {"channel": name, "address": name, "memberships": []})
    memberships: list[dict[str, Any]] = entry["memberships"]
    for index, held in enumerate(memberships):
        if (held["system"], held["family"]) == (membership["system"], membership["family"]):
            memberships[index] = membership
            return
    memberships.append(membership)


class MiddleLayerDatabase(BaseDatabase):
    """
    Database for middle-layer (MML) style channel organization.

    Supports functional hierarchy with optional device/sector filtering.
    Designed for React agent-style exploration using query tools.
    """

    # Populated by load_database(); its isinstance check guards the shape.
    data: dict[str, Any]

    def __init__(self, db_path: str) -> None:
        """
        Initialize middle layer database.

        Args:
            db_path: Path to middle layer database JSON file
        """
        super().__init__(db_path)

    def load_database(self) -> None:
        """Load middle layer database from JSON file.

        Raises:
            ValueError: The file is valid JSON in a shape this parser does not
                read. Raised rather than read as an empty tree: every consumer
                turns a loader exception into a corrupt-source verdict, while a
                database that "loaded" zero channels is indistinguishable from
                an empty facility.
        """
        with open(self.db_path) as f:
            self.data = json.load(f)

        if not isinstance(self.data, dict):
            raise ValueError(
                "Invalid database format: a middle-layer database is a dict of "
                "systems -> families -> fields, keyed by name at every level; this "
                f"file's root is a {type(self.data).__name__}. See "
                "data/channel_finder/middle_layer.json for the "
                "expected format."
            )

        # Build flat channel map for validation and lookup
        self.channel_map = self._build_channel_map()

    def _build_channel_map(self) -> dict[str, dict]:
        """
        Flatten MML hierarchy into channel map for O(1) validation.

        Keys starting with ``_`` are metadata (``_description``, ``_meta``) at
        any level and are skipped, as is the top-level ``schema`` key that
        names the index's document. Any other value that is not a mapping is a
        shape error, and is named rather than skipped: a system or family that
        silently contributed nothing would read as a facility with fewer
        channels, not as a broken file.

        A channel is keyed once, however many families list it: its entry is
        ``{"channel", "address", "memberships"}``, one membership
        (``system``, ``family``, ``field``, ``subfield``, ``description``,
        ``protocol`` and the field's metadata) per (System, Family) that lists
        it, in document order.

        Returns:
            Dict mapping channel names to their entries

        Raises:
            ValueError: A system or family whose value is not a mapping.
        """
        channels: dict[str, dict[str, Any]] = {}

        for system, families in self.data.items():
            if system.startswith("_") or system in DOCUMENT_KEYS:
                continue
            if not isinstance(families, dict):
                raise ValueError(
                    f"Invalid database format: system '{system}' must map family "
                    f"names to their fields, got a {type(families).__name__}. See "
                    "data/channel_finder/middle_layer.json for the "
                    "expected format."
                )

            for family, fields in families.items():
                if family.startswith("_"):
                    continue
                if not isinstance(fields, dict):
                    raise ValueError(
                        f"Invalid database format: family '{system}:{family}' must "
                        f"map field names to their definitions, got a "
                        f"{type(fields).__name__}. See "
                        "data/channel_finder/middle_layer.json for the "
                        "expected format."
                    )

                # Process each field in the family
                self._extract_channels_from_field(channels, system, family, fields, path=[])

        return channels

    def _extract_channels_from_field(
        self,
        channels: dict[str, dict],
        system: str,
        family: str,
        field_data: dict,
        path: list[str],
    ) -> None:
        """
        Recursively extract channels from nested field structure.

        Handles the MATLAB Middle Layer export format which includes:
        - ChannelNames: List of PV addresses (may contain whitespace padding)
        - Metadata fields: DataType, Mode, Units, HW2PhysicsParams, etc.
        - Special fields: setup (device metadata), pyAT (accelerator physics)

        Args:
            channels: Accumulator dict for channel map
            system: Current system name
            family: Current family name
            field_data: Current field/subfield data
            path: Current path through field hierarchy (e.g., ["Monitor"] or ["Setpoint", "X"])
        """
        for key, value in field_data.items():
            # Skip setup and special metadata fields
            # Note: 'pyAT' is skipped because it has ATIndex instead of ChannelNames
            if key.lower() in ["setup", "_setup", "pyat"]:
                continue

            if not isinstance(value, dict):
                continue

            # Check if this is a terminal field carrying a channel key
            present_keys = [channel_key for channel_key in CHANNEL_KEYS if channel_key in value]
            if present_keys:
                # Protocol per channel key, aligned with CHANNEL_KEYS order
                key_protocols = dict(zip(CHANNEL_KEYS, ("ca", "tango"), strict=True))
                channel_names: list[tuple[str, str]] = []
                for channel_key in present_keys:
                    names = value[channel_key]
                    # Normalize string to list (MML exports may use string for single channels)
                    for name in [names] if isinstance(names, str) else names:
                        channel_names.append((name, key_protocols[channel_key]))
                field_path = path + [key]

                # Extract metadata if present (preserve from MML exports)
                metadata = {}
                for meta_key in [
                    "DataType",
                    "Mode",
                    "Units",
                    "HWUnits",
                    "PhysicsUnits",
                    "MemberOf",
                    "Range",
                    "Tolerance",
                    "Description",
                ]:
                    if meta_key in value:
                        metadata[meta_key] = value[meta_key]

                # Record each channel's membership of this family with the
                # field's metadata. A name listed under several keys of this
                # field keeps the protocol of the first key in CHANNEL_KEYS order.
                field_names: set[str] = set()
                for channel_name, protocol in channel_names:
                    # Strip whitespace from channel names (MML exports have padding)
                    clean_name = channel_name.strip()
                    if clean_name and clean_name not in field_names:
                        field_names.add(clean_name)
                        _add_membership(
                            channels,
                            clean_name,
                            {
                                "system": system,
                                "family": family,
                                "field": field_path[0] if field_path else "",
                                "subfield": field_path[1:] if len(field_path) > 1 else None,
                                "description": f"{system}:{family}:{':'.join(field_path)}",
                                "protocol": protocol,
                                **metadata,  # Include MML metadata if present
                            },
                        )
            else:
                # Recurse into nested structure (handles subfields)
                self._extract_channels_from_field(channels, system, family, value, path + [key])

    def get_channel(self, channel_name: str) -> dict | None:
        """
        Get channel information by name.

        Args:
            channel_name: Channel name to lookup

        Returns:
            The channel's entry, whose ``memberships`` list every
            (System, Family) that lists it, or None if not found
        """
        return self.channel_map.get(channel_name.strip())

    def get_all_channels(self) -> list[dict]:
        """
        Get all channels in the database.

        Returns:
            List of channel dictionaries
        """
        return list(self.channel_map.values())

    def validate_channel(self, channel_name: str) -> bool:
        """
        Check if a channel exists.

        Args:
            channel_name: Channel name to validate

        Returns:
            True if channel exists, False otherwise
        """
        return channel_name.strip() in self.channel_map

    def get_statistics(self) -> dict:
        """
        Get database statistics.

        Returns:
            Dict with statistics (total_channels, systems, families, etc.)
        """
        # Count systems
        systems = [s for s in self.data.keys() if isinstance(self.data[s], dict)]

        # Count families across all systems
        all_families = set()
        for system in systems:
            if isinstance(self.data[system], dict):
                families = [
                    f for f in self.data[system].keys() if isinstance(self.data[system][f], dict)
                ]
                all_families.update(families)

        return {
            "total_channels": len(self.channel_map),
            "format": "middle_layer",
            "systems": len(systems),
            "families": len(all_families),
        }

    # === Tool support methods for React agent ===

    def list_systems(self) -> list[dict[str, str]]:
        """
        Get list of all system names with descriptions.

        Returns:
            List of dicts with 'name' and 'description' keys.
            Description is empty string if not provided in database.
        """
        systems = []
        for s in self.data.keys():
            if isinstance(self.data[s], dict):
                systems.append({"name": s, "description": self.data[s].get("_description", "")})
        return systems

    def list_families(self, system: str) -> list[dict[str, str]]:
        """
        Get list of families in a system with descriptions.

        Args:
            system: System name

        Returns:
            List of dicts with 'name' and 'description' keys.
            Description is empty string if not provided in database.

        Raises:
            ValueError: If system not found
        """
        if system not in self.data or not isinstance(self.data[system], dict):
            available = [s["name"] for s in self.list_systems()]
            raise ValueError(f"System '{system}' not found. Available systems: {available}")

        families = []
        for f in self.data[system].keys():
            if f.startswith("_"):  # Skip metadata keys
                continue
            if isinstance(self.data[system][f], dict):
                families.append(
                    {"name": f, "description": self.data[system][f].get("_description", "")}
                )
        return families

    def inspect_fields(
        self, system: str, family: str, field: str | None = None
    ) -> dict[str, dict[str, str]]:
        """
        Inspect field structure with types and descriptions.

        Args:
            system: System name
            family: Family name
            field: Optional field name to inspect (if None, shows top-level fields)

        Returns:
            Dict mapping field names to dicts with 'type' and 'description' keys.
            Description is empty string if not provided in database.

        Raises:
            ValueError: If system/family/field not found
        """
        # Validate system
        if system not in self.data:
            raise ValueError(f"System '{system}' not found")

        # Validate family
        if family not in self.data[system]:
            families = [f["name"] for f in self.list_families(system)]
            raise ValueError(
                f"Family '{family}' not found in system '{system}'. Available families: {families}"
            )

        family_data = self.data[system][family]

        # If specific field requested, inspect that field
        if field:
            if field not in family_data:
                available = [
                    k for k in family_data.keys() if not k.startswith("_") and k.lower() != "setup"
                ]
                raise ValueError(
                    f"Field '{field}' not found in '{system}:{family}'. "
                    f"Available fields: {available}"
                )

            field_data = family_data[field]
            result = {}

            if isinstance(field_data, dict):
                for key, value in field_data.items():
                    # Skip metadata and setup blocks; neither is a subfield
                    if key.startswith("_") or key.lower() == "setup":
                        continue
                    if isinstance(value, dict):
                        # Label a channel-keyed subfield by its first present key
                        channel_key = next((k for k in CHANNEL_KEYS if k in value), None)
                        result[key] = {
                            "type": channel_key or "dict (subfield)",
                            "description": value.get("_description")
                            or value.get("Description", ""),
                        }
                    else:
                        result[key] = {"type": type(value).__name__, "description": ""}

            return result

        # Otherwise show top-level fields
        result = {}
        for key, value in family_data.items():
            if key.startswith("_"):  # Skip metadata
                continue
            if key.lower() == "setup":
                result[key] = {
                    "type": "metadata",
                    "description": "Device setup information (CommonNames, DeviceList)",
                }
            elif isinstance(value, dict):
                # Label a channel-keyed field by its first present key
                channel_key = next((k for k in CHANNEL_KEYS if k in value), None)
                result[key] = {
                    "type": channel_key or "dict (has subfields)",
                    "description": value.get("_description") or value.get("Description", ""),
                }
            else:
                result[key] = {"type": type(value).__name__, "description": ""}

        return result

    def list_channel_names(
        self,
        system: str,
        family: str,
        field: str,
        subfield: str | None = None,
        sectors: list[int] | None = None,
        devices: list[int] | None = None,
        *,
        protocol: str | None = None,
    ) -> list[str]:
        """
        Get channel names for a specific field/subfield with optional filtering.

        Args:
            system: System name
            family: Family name
            field: Field name
            subfield: Optional subfield name
            sectors: Optional list of sector numbers to filter by
            devices: Optional list of device numbers to filter by
            protocol: ``"ca"`` for the ``ChannelNames`` list or ``"tango"`` for
                the ``TangoNames`` list. When omitted, the list under the first
                present key in ``CHANNEL_KEYS`` order is returned.

        Returns:
            List of channel names

        Raises:
            ValueError: If path not found or invalid, if ``protocol`` is not a
                known protocol, or if the requested protocol's key is absent
                (the message names the keys the field does carry).
        """
        # Channel key per protocol, aligned with CHANNEL_KEYS order
        protocol_keys = dict(zip(("ca", "tango"), CHANNEL_KEYS, strict=True))
        if protocol is not None and protocol not in protocol_keys:
            raise ValueError(
                f"Unknown protocol '{protocol}'. Known protocols: {sorted(protocol_keys)}"
            )

        # Navigate to field
        if system not in self.data:
            raise ValueError(f"System '{system}' not found")

        if family not in self.data[system]:
            raise ValueError(f"Family '{family}' not found in system '{system}'")

        family_data = self.data[system][family]

        if field not in family_data:
            raise ValueError(f"Field '{field}' not found in '{system}:{family}'")

        field_data = family_data[field]

        # If subfield specified, navigate deeper
        if subfield:
            if not isinstance(field_data, dict) or subfield not in field_data:
                raise ValueError(f"Subfield '{subfield}' not found in '{system}:{family}:{field}'")
            field_data = field_data[subfield]

        location = f"{system}:{family}:{field}" + (f":{subfield}" if subfield else "")
        present_keys = (
            [key for key in CHANNEL_KEYS if key in field_data]
            if isinstance(field_data, dict)
            else []
        )

        # Get channel names from the requested protocol's key, or the first present
        if protocol is None:
            channel_key = present_keys[0] if present_keys else None
            if channel_key is None:
                raise ValueError(f"No {' or '.join(CHANNEL_KEYS)} found at '{location}'")
        else:
            channel_key = protocol_keys[protocol]
            if channel_key not in present_keys:
                raise ValueError(
                    f"No {channel_key} (protocol '{protocol}') found at '{location}'. "
                    f"Channel keys present: {present_keys}"
                )

        channel_names = field_data[channel_key]
        # Normalize string to list (MML exports may use string for single channels)
        if isinstance(channel_names, str):
            channel_names = [channel_names]

        # Apply filtering if requested
        if sectors or devices:
            channel_names = self._filter_by_device_sectors(
                system, family, channel_names, sectors, devices
            )

        # Strip whitespace and filter empty strings
        return [name.strip() for name in channel_names if name.strip()]

    def _filter_by_device_sectors(
        self,
        system: str,
        family: str,
        channel_names: list[str],
        sectors: list[int] | None,
        devices: list[int] | None,
    ) -> list[str]:
        """
        Filter channel names by device and sector numbers.

        Args:
            system: System name
            family: Family name
            channel_names: Full list of channel names
            sectors: Optional list of sectors to include
            devices: Optional list of devices to include

        Returns:
            Filtered list of channel names

        Raises:
            ValueError: If DeviceList not available or filtering fails
        """
        # Get DeviceList from setup
        family_data = self.data[system][family]
        setup = get_setup(family_data)
        device_list = setup.get("DeviceList")

        if not device_list:
            raise ValueError(
                f"Cannot filter by sectors/devices for '{system}:{family}' - "
                f"DeviceList not defined in database"
            )

        if len(channel_names) != len(device_list):
            raise ValueError(
                f"ChannelNames length ({len(channel_names)}) does not match "
                f"DeviceList length ({len(device_list)}) for '{system}:{family}'"
            )

        # Build filtered list
        filtered = []
        sectors_set = set(sectors) if sectors else None
        devices_set = set(devices) if devices else None

        for i, (channel_name, device_entry) in enumerate(
            zip(channel_names, device_list, strict=True)
        ):
            if not isinstance(device_entry, list) or len(device_entry) != 2:
                raise ValueError(f"Invalid DeviceList entry at index {i}: {device_entry}")

            sector, device = device_entry

            # Check filters
            sector_match = sectors_set is None or sector in sectors_set
            device_match = devices_set is None or device in devices_set

            if sector_match and device_match:
                filtered.append(channel_name)

        if not filtered:
            raise ValueError(
                f"No channels match filter criteria. "
                f"Requested sectors: {sectors}, devices: {devices}"
            )

        return filtered

    def get_common_names(self, system: str, family: str) -> list[str] | None:
        """
        Get common/friendly names for devices in a family.

        Args:
            system: System name
            family: Family name

        Returns:
            List of common names or None if not available
        """
        if system not in self.data or family not in self.data[system]:
            return None

        family_data = self.data[system][family]
        setup = get_setup(family_data)
        return setup.get("CommonNames")

    def get_device_info(self, system: str, family: str) -> dict:
        """Get device arrangement info for a family.

        Args:
            system: System name.
            family: Family name.

        Returns:
            Dict with common_names, device_list, sectors, devices_per_sector,
            and total_devices.
        """
        empty: dict[str, Any] = {
            "common_names": None,
            "device_list": None,
            "sectors": [],
            "devices_per_sector": {},
            "total_devices": 0,
        }
        if system not in self.data or family not in self.data[system]:
            return empty

        setup = get_setup(self.data[system][family])
        common_names = setup.get("CommonNames")
        device_list = setup.get("DeviceList")

        if not device_list:
            return {**empty, "common_names": common_names}

        from collections import Counter

        sector_counts = Counter(entry[0] for entry in device_list if len(entry) >= 2)
        sectors = sorted(sector_counts.keys())

        return {
            "common_names": common_names,
            "device_list": device_list,
            "sectors": sectors,
            "devices_per_sector": dict(sector_counts),
            "total_devices": len(device_list),
        }

    # === Persistence ===

    def _serialize(self) -> dict:
        """Serialize the MML tree back to JSON-compatible dict."""
        return self.data
