"""The artifacts generated from the facility schema, and the model they give.

``_generated/core.py`` and ``_generated/vocabulary.json`` are committed; each
test here regenerates them from a copy of ``core.yaml`` and ``vocabulary.yaml``
alone and compares the bytes, so a schema edit without a regeneration fails.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = REPO_ROOT / "src" / "osprey" / "facility" / "schema"
GENERATED_DIR = SCHEMA_DIR / "_generated"

#: The lines above gen-pydantic's output in the committed ``core.py``.
CORE_HEADER = (
    "# Generated by `gen-pydantic core.yaml` (linkml 1.11.1), run from\n"
    "# src/osprey/facility/schema/; everything below these three lines is its\n"
    "# stdout, byte for byte. Edit core.yaml or vocabulary.yaml, never this file.\n"
)


@pytest.fixture(scope="module")
def schema_copy(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A directory holding only ``core.yaml`` and ``vocabulary.yaml``."""
    directory = tmp_path_factory.mktemp("schema")
    for name in ("core.yaml", "vocabulary.yaml"):
        shutil.copyfile(SCHEMA_DIR / name, directory / name)
    return directory


def _run(args: list[str], cwd: Path) -> str:
    result = subprocess.run(
        [sys.executable, *args], cwd=cwd, capture_output=True, text=True, check=False
    )
    assert result.returncode == 0, result.stderr
    return result.stdout


# --- the committed artifacts ----------------------------------------------------


def test_core_is_gen_pydantic_output_of_the_schema(schema_copy: Path) -> None:
    stdout = _run(
        ["-c", "from linkml.generators.pydanticgen import cli; cli()", "core.yaml"],
        cwd=schema_copy,
    )
    committed = (GENERATED_DIR / "core.py").read_text(encoding="utf-8")
    assert committed == CORE_HEADER + stdout, (
        "_generated/core.py is stale: from src/osprey/facility/schema/ run "
        "`gen-pydantic core.yaml` and keep the three header lines above its output"
    )


def test_package_imports_without_warnings() -> None:
    _run(["-W", "error", "-c", "import osprey.facility.schema"], cwd=REPO_ROOT)


# --- the model ------------------------------------------------------------------


def _limits(addresses: list[str]) -> dict[str, Any]:
    return {
        "defaults": {"writable": False, "confirm": True},
        "records": [{"address": address, "writable": False} for address in addresses],
    }


def _zero_source() -> dict[str, Any]:
    """The facility file a tree without sources builds."""
    return {
        "schema": "osprey.facility.facility/1",
        "identity": {"code": "my_proj", "name": "my proj"},
        "classes": [],
        "places": [],
        "devices": [],
        "channels": [],
        "groups": [],
        "models": [{"name": "texture", "engine": "texture"}],
        "limits": _limits([]),
        "scenarios": [],
    }


def _two_channel() -> dict[str, Any]:
    """Two untagged readbacks and nothing else."""
    document = _zero_source()
    addresses = ["DEMO:ONE", "DEMO:TWO"]
    document["channels"] = [{"id": address, "role": "readback"} for address in addresses]
    document["limits"] = _limits(addresses)
    return document


def _two_channel_scenario_measurement() -> dict[str, Any]:
    """The two-channel file with one scenario and one model measurement block."""
    document = _two_channel()
    document["models"] = [
        {
            "name": "optics",
            "engine": "pyat",
            "deck": "decks/optics/lattice.m",
            "measurement": {
                "kinds": ["orm"],
                "groups": {"bpm": "BPM", "hcor": "HCM", "vcor": "VCM"},
                "instruments": {"tune": "DEMO:ONE"},
                "n_step": 2,
                "corrector_delta": 0.001,
                "sleep_between_step": 0.5,
            },
        },
        {"name": "texture", "engine": "texture"},
    ]
    document["scenarios"] = [
        {"name": "warm", "overrides": {"DEMO:ONE": 1.5}, "faults": {}, "logbook": []}
    ]
    return document


@pytest.mark.parametrize(
    "document",
    [_zero_source(), _two_channel(), _two_channel_scenario_measurement()],
    ids=["zero-source", "two-channel", "two-channel-scenario-measurement"],
)
def test_facility_files_validate(document: dict[str, Any]) -> None:
    from osprey.facility.schema import Facility

    facility = Facility.model_validate(document)
    assert facility.schema == document["schema"]


def test_unknown_key_fails_validation() -> None:
    from pydantic import ValidationError

    from osprey.facility.schema import Facility

    document = _two_channel()
    document["channels"][0]["kind"] = "magnet"
    with pytest.raises(ValidationError) as caught:
        Facility.model_validate(document)
    assert [error["type"] for error in caught.value.errors()] == ["extra_forbidden"]
    assert caught.value.errors()[0]["loc"] == ("channels", 0, "kind")


def test_unknown_top_level_key_fails_validation() -> None:
    from pydantic import ValidationError

    from osprey.facility.schema import Facility

    document = _zero_source()
    document["kind"] = "facility"
    with pytest.raises(ValidationError) as caught:
        Facility.model_validate(document)
    assert [error["type"] for error in caught.value.errors()] == ["extra_forbidden"]
